### ISSUE TITLE
archiveinfo() UnsupportedCompressionMethodError with BCJ archive

### ISSUE THREAD

**Issue by ganego** [miurahr/py7zr#100]
**Describe the bug**
py7zr throws UnsupportedCompressionMethodError when opening a file and retrieving .archiveinfo()

**To Reproduce**
Create a BCJ archive: `7z a -mf=BCJ test.7z test.txt` (create some test.txt before...)
Verify with 7z that it's BCJ - my archive was LZMA:12k BCJ.
Open file with 7zr and use archiveinfo().

``` Python
import py7zr
archive = py7zr.SevenZipFile('test.7z', 'r').archiveinfo()
```

Crash:
```
File "...\py7zr\compression.py", line 433, in get_methods_names
    methods_names.append(methods_name_map[coder['method']])
KeyError: b'\x03\x03\x01\x03'
```

**Environment (please complete the following information):**
 - OS: W7x64
 - Python: 3.8.1 x64
 - py7zr version: https://github.com/miurahr/py7zr/tree/1a1c07fe83937478b48cbdb90fbb0d1ce8765ee0 (aka the newest master as of today)

**Comment by miurahr** [comment]
I cannot reproduce with a file that produced by a procedure you post. A produced files become 'LZMA2:BCJ' in my environment.

I've just create another file by` 7z a -m1=LZMA -mf=BCJ test.7z test1.txt`. Is it produce a same error you got?
[a.zip](https://github.com/miurahr/py7zr/files/4301427/a.zip)

**Comment by ganego** [comment]
With the fixes applied I no longer get any crashes for several different BCJ archives I created. 

But I tested another variant that still crashes. See this site: https://sevenzip.osdn.jp/chm/cmdline/switches/method.htm and scroll down to `Supported filters` for 7z.

BCJ2 crashes with `Unknown method b'\x03\x03\x01\x1b'`  
All other tested filters work fine with either LZMA or LZMA2.

**Comment by miurahr** [comment]
Python core do not support BCJ2. so py7zr also not support it.
If you want to support, please contribute to liblzma, which is linked with python core library.

**Comment by ganego** [comment]
It should still not crash .archiveinfo(). It should just return the requested information about the archive.
If extracting is not supported that is fine, but should raise an exception when extracting, not when requesting archive information.
For example I do not need to extract anything, I just need information if an archive is solid.  
Thank you

**Comment by miurahr** [comment]
It is not crash, You should try-catch py7zr.exceptions.UnsupportedCompressionMethodError  properly.
