### ISSUE TITLE
No password encrypted on write

### ISSUE THREAD

**Issue by smogol** [miurahr/py7zr#109]
I tried to write files to compressed archive an with password set but the files where not accessible.
code snip:
`c7zip_file = py7zr.SevenZipFile(c7z_file_name, mode='w', password='somepassword')`
`for fname in compressed_files:`
`    c7zip_file.write(fname)`
`c7zip_file.close()`

**Comment by miurahr** [comment]
There is no support for encrypted write. contributions are welcome.

**Comment by miurahr** [comment]
Now it raises NotImplementedError
