### ISSUE TITLE
Extract file to buffer

### ISSUE THREAD

**Issue by Zoynels** [miurahr/py7zr#110]
**Is your feature request related to a problem? Please describe.**
I need to get file from archive and work with it in memory. Now first I should extract file into temporary folder and then read extracted file. So there are two io: first write to disk, second read from disk uncompressed file.

**Describe the solution you'd like**
Some way to extract file into io.BytesIO() without write/read temporary file to disk.

**Describe alternatives you've considered**
Or archive could be extracted into dict of io.BytesIO(), where keys are filepath and values are io.BytesIO()

**Additional context**
None

**Comment by miurahr** [comment]
Thank you for PR! I've put  a change request for that.

**Comment by miurahr** [comment]
Merged.
