### ISSUE TITLE
Archive with links like symlinks stores links with absolute path

### ISSUE THREAD

**Issue by Zoynels** [miurahr/py7zr#112]
**Describe the bug**
I don't is this bug or feature, but for archive with links like symlinks if file is not in same folder, then it stores links with absolute path.

**To Reproduce**
1. Prepare test data:
```
import os, pathlib

parent_path_drive = "X:/"
parent_path = os.path.join(parent_path_drive, "symb")

with open(os.path.join(parent_path, "Original1.txt"), "w") as f:
    f.write("real Original1.txt")

s = pathlib.Path(os.path.join(parent_path, "rel/path/link_to_Original1.txt"))
s.parent.mkdir(parents=True, exist_ok=True)
s.symlink_to(os.path.join(parent_path, "Original1.txt"), False)

s = pathlib.Path(os.path.join(parent_path, "rel/path/link_to_link_Original1.txt"))
s.parent.mkdir(parents=True, exist_ok=True)
s.symlink_to(os.path.join(parent_path, "rel/path/link_to_Original1.txt"), False)

s = pathlib.Path(os.path.join(parent_path, "rel/path/link_to_link_to_link_Original1.txt"))
s.parent.mkdir(parents=True, exist_ok=True)
s.symlink_to(os.path.join(parent_path, "rel/path/link_to_link_Original1.txt"), False)

s = pathlib.Path(os.path.join(parent_path, "rel/link_to_link_to_link_Original1.txt"))
s.parent.mkdir(parents=True, exist_ok=True)
s.symlink_to(os.path.join(parent_path, "rel/path/link_to_link_Original1.txt"), False)

s = pathlib.Path(os.path.join(parent_path, "a/rel64"))
s.parent.mkdir(parents=True, exist_ok=True)
s.symlink_to(os.path.join(parent_path, "rel"), True)


s = pathlib.Path(os.path.join(parent_path, "lib/Original2.txt"))
s.parent.mkdir(parents=True, exist_ok=True)
with open(os.path.join(parent_path, "lib/Original2.txt"), "w") as f:
    f.write("real Original2.txt")

s = pathlib.Path(os.path.join(parent_path, "lib/Original2.[1.2.3].txt"))
s.parent.mkdir(parents=True, exist_ok=True)
s.symlink_to(os.path.join(parent_path, "lib/Original2.txt"), False)

s = pathlib.Path(os.path.join(parent_path, "lib/Original2.[1.2].txt"))
s.parent.mkdir(parents=True, exist_ok=True)
s.symlink_to(os.path.join(parent_path, "lib/Original2.[1.2.3].txt"), False)

s = pathlib.Path(os.path.join(parent_path, "lib/Original2.[1].txt"))
s.parent.mkdir(parents=True, exist_ok=True)
s.symlink_to(os.path.join(parent_path, "lib/Original2.[1.2].txt"), False)

s = pathlib.Path(os.path.join(parent_path, "lib64"))
s.symlink_to(os.path.join(parent_path, "lib"), True)


s = pathlib.Path(os.path.join(parent_path_drive, "Original3.txt"))
s.parent.mkdir(parents=True, exist_ok=True)
with open(os.path.join(parent_path_drive, "Original3.txt"), "w") as f:
    f.write("real Original3.txt")

s = pathlib.Path(os.path.join(parent_path, "Original3.[1].txt"))
s.parent.mkdir(parents=True, exist_ok=True)
s.symlink_to(os.path.join(parent_path_drive, "Original3.txt"), False)
```
2. Run following code with python3.
```
import py7zr, os

os.chdir(parent_path)
archive = py7zr.SevenZipFile(os.path.join(parent_path_drive, "symb_2.7z"), 'w')
archive.writeall('', '')
archive.close()
```
3. symb_2.7z is produced
file in archive [symb_2_2.zip](https://github.com/miurahr/py7zr/files/4463967/symb_2_2.zip)

4. open archive in 7zip and view links which saved into body of files
for file "Original3.[1].txt" link is to "\\?\X:\Original3.txt"
for folder "a\rel64" link is to "\\?\X:\symb\rel"
and etc.

**Expected behavior**
1. There should be option to write files instead of links (I can't found)
2. If files are in archive there should be relative path to this files ["Original1.txt" in thise issue]
3. If original files are in external folder ["Original3.txt" in thise issue] then should write real files instead of links (another option).
4. Add such archive to test/data to test symlinks/hardlinks/junction with different file/folder locations

**Environment (please complete the following information):**
 - OS: [Windows 10]
 - Python 3.8.2 | packaged by conda-forge | (default, Mar  5 2020, 17:29:01) [MSC v.1916 64 bit (AMD64)] on win32
 - py7zr version: [v0.6, commit #1e38828 on master]

**Comment by miurahr** [comment]
Could you create a sample sevenzip archive with symbolic link by another tool than py7zr on windows?
I'd like to analyze the sample and add more test case against making archive with links.

A test suite skip links test on windows because making links on windows requires special privileges for user. But now I've added a condition check for test whether test user have a privileges or not, and if not, test will skip.

**Comment by Zoynels** [comment]
Sorry, but curent standart 7-Zip programm not work with links on windows.
In current version "19.00 / 2019-02-21" and "20.00 alpha / 2020-02-06" it creates empty files.
[symb (created by 7-zip 20.00 alpha).zip](https://github.com/miurahr/py7zr/files/4465992/symb.created.by.7-zip.20.00.alpha.zip)
I don't know another programm which archives 7z

**Comment by miurahr** [comment]
Now I can reproduce a case in #113  Here is an evidence: https://ci.appveyor.com/project/miurahr/py7zr/builds/32273918

**Comment by miurahr** [comment]
I have updated #113
Does the test case reproduce your (@Zoynels )  issue?

**Comment by miurahr** [comment]
I am wondering that your  procedure makes really create symbolic link with relative path?

After running a procedure following part,
```
import os, pathlib

parent_path_drive = "X:/"
parent_path = os.path.join(parent_path_drive, "symb")

with open(os.path.join(parent_path, "Original1.txt"), "w") as f:
    f.write("real Original1.txt")

s = pathlib.Path(os.path.join(parent_path, "rel/path/link_to_Original1.txt"))
s.parent.mkdir(parents=True, exist_ok=True)
s.symlink_to(os.path.join(parent_path, "Original1.txt"), False)
```

command dir said

```
Z:\symb\rel\path>dir

Directory  Z:\symb\rel\path

2020/05/07  10:05    <DIR>          .
2020/05/07  10:05    <DIR>          ..
2020/05/07  10:05    <SYMLINK>      link_to_Original1.txt [z:/symb\Original1.txt]
```

It seems symlink has an ABSOLUTE path not relative.

**Comment by Zoynels** [comment]
Function creates standart link (so it could be absolute).

The main ptoblem is that there is the situation:
1. User1 need to send data to the user2
2. User1 / someone else created symbolic links (absolute or relative is not so important).
3. User1 create an archive in which some files / folders got with a symbolic link to the files / folders that did not actually stored into the archive.

Now:
4. User2 recieve archive and unpacks it and really creates symbolic links which could be to non existent files/folders/drivers... Maybe we want user2 to create links maybe not. But I think the situation is that we doesn’t send real files and user don't recieve files which we send to him. It's like sending a shortcut to a file instead of a file.

Expected behavior:
3.1. If file in archive exist several times: one time real file and second time symlink to it. Then we store real file and symlink to file in archive. I think there should be relative path (may be always from root of archive) so we exactly know that we extract then symlink will be to extracted file.
3.2. If file in archive exist only as symlink and no real file is archived -- then user should have option: store "real symlinks to maybe to nonexistent files" or "replace symlinks to nonexistent files with real files".
4. If archiver get option "replace symlinks to nonexistent files with real files" then when user unpacks the archive, he will receive a full copy of the file, and not a shortcut that refers to an empty space, because the user does not have a file. Yes, there breaks links, but user will recieve real data instead shortcut.

Result:
When creating an archive, understand that when unpacking there is a link to a file that is in the archive, then we leave a link (in principle, the link should be to the unpacked file, and not to the one that the user had, because the unpacking paths may differ). If there is no link to the file, then we need to replace the link with a real file.

**Comment by miurahr** [comment]
I am wondering another question,  why a process to reproduce is such complex which create many files? 
Why the problem is not able to reproduce with small number of files?  

And thank you for your explanation of  YOUR situation, but it is not a description of a problem py7zr have.

**Comment by miurahr** [comment]
You can easily break it without py7zr with absolute symbolic link path.

```
Z:\> ren symb symc

Z:\> cd smbc\rel\path

Z:\symc\rel\path> dir

2020/05/07  10:14    <SYMLINK>      another_link_to_Original1.txt [..\..\Original1.txt]
2020/05/07  10:05    <SYMLINK>      link_to_Original1.txt [z:/symb\Original1.txt]

Z:\symc\rel\path>type link_to_Original1.txt
File not found.

Z:\symc\rel\path>type another_link_to_Original1.txt
real original1.txt.

```

It seems not to be a bug on py7zr.

**Comment by miurahr** [comment]
I have tested with[ 'p7zip' ](https://sourceforge.net/projects/p7zip/) which supports symbolic link and which is build upon 7zip originators code base.

It produce an archive as same as py7zr does.
p7zip produce ABSOLUTE link for a symbolic link to absolute path, which is as same as you create, and it produce relative link for a symbolic link to relative path.

I would like to decide it is invalid and py7zr does work as well as p7zip.
