### ISSUE TITLE
Make the API more like core libraries

### ISSUE THREAD

**Issue by andrebrait** [miurahr/py7zr#117]
**Is your feature request related to a problem? Please describe.**
The current API is not bad, although I do think there's some confusion when dealing with the list of file information objects the archive keeps internally. However, given Python already has a few libraries to deal with file compression/decompression/archival, such as `zipfile` and `tarfile`, and the fact that there are other 3rd party libraries that use a similar API as well, such as `rarfile`, pursuing something similar in this project might be something to consider.

Given the fact Python 2.x has been EOL'd, future versions of this library might just target Python 3, which will make things a lot easier when pursuing such change.

**Describe the solution you'd like**
Adapting the API in order to make it more like `zipfile` and `tarfile`.

**Describe alternatives you've considered**
There are no current alternative solutions capable of handling 7z files in the way I want.

**Additional context**
[Python's zipfile library](https://docs.python.org/3/library/zipfile.html)
[Python's tarfile library](https://docs.python.org/3/library/tarfile.html)
[rarfile library](https://github.com/markokr/rarfile)

I'm pretty sure you are familiar with these, but I am not sure if not using a similar API was a deliberate choice or not.

**Comment by miurahr** [comment]
Here is a big difference of 7zip from zip and tar, which is a lack of  random access mode for archive files. 7zip default is a "solid" compression which means when user want  a part of archive fie, py7zr need extract whole of archive from start and pass a partial data to user.
  It is why API has a difference. e.g. 'zipfile.extract(filename)' and 'sevenzipfile.extract(filefilter)' it  has designed to avoid multiple read of archive data. 

If you have a better idea to solve the problem, you are welcome to propose it here.

**Comment by andrebrait** [comment]
Got it. In this case, extracting to a temp directory might be better, indeed. I'm wrapping it up like this:

https://github.com/andrebrait/1g1r-romset-generator/blob/a85f4f180d3f84f1e3084accbaaad66830b783af/modules/archive.py#L229-L293

**Comment by miurahr** [comment]
Thank you for feed back. User can solve a situation by extracting  archive in temp directory.
