### ISSUE TITLE
Include CRC32 in FileInfo

### ISSUE THREAD

**Issue by myers** [miurahr/py7zr#135]
**Is your feature request related to a problem? Please describe.**
I would like to get the crc32 of a file without having to extract it.

**Describe the solution you'd like**
Add `crc32` as a field on `FileInfo`

**Describe alternatives you've considered**
I suspect this is already in some deeper structure of py7zr, but I don't understand enough to find it.  I know it is listed when doing `7z l -slt file.7z`.

**Comment by miurahr** [comment]
There are several CRC value in 7zip archive. Which one should include?

- startheadercrc
- nextheadercrc
- each archive file crcs[] (optional)
- each folders(lzma containers) crc[]  (optional)

Mandatory CRC is header crc and it may be not good for FileInfo.

**Comment by miurahr** [comment]
Oh,

> ** the crc32 of a file **

It is optional field.

**Comment by myers** [comment]
Have you ever used the built in python module `zipfile` or https://pypi.org/project/rarfile/ ?  Both of these allow you to get the crc32 of the files in the archive, as they are in the metadata of the archive.

I was able to find what I needed:

```
        self._zf = py7zr.SevenZipFile(self.filepath, "r")
        # later in the class
        for fi in self._zf.list():
            if fi.is_directory:
                assert fi.uncompressed == 0
                continue

            fnfo = dict(filepath=fi.filename, size=fi.uncompressed)
            for ff in self._zf.header.files_info.files:
                if ff["filename"] != fi.filename:
                    continue
                crc32_uint32 = ctypes.c_uint32(0)
                crc32_uint32.value = ff["digest"]
                fnfo["crc32"] = f"{crc32_uint32.value:08X}"

```

**Comment by miurahr** [comment]
7zip do not have a crc as a metadata.

**Comment by myers** [comment]
Very odd, the code above gives me the CRC32 of the file in the archive.  If it's not in the metadata of the archive, where is it getting it from?

**Comment by miurahr** [comment]
You may mean

> each archive file crcs[] (optional)

**Comment by myers** [comment]
> You may mean
> 
> > each archive file crcs[] (optional)

Yes, sorry.  That is what I'm looking for.

**Comment by miurahr** [comment]
Sorry, just now, I cannot find a place where is a filed of CRC for each Files info in header.files_info.files.

Here is a header decode block for files_info

https://github.com/miurahr/py7zr/blob/a2971e450331330c98c5ca0c109563f684d60f60/py7zr/archiveinfo.py#L682-L736

**Comment by miurahr** [comment]
Maybe around L463.
https://github.com/miurahr/py7zr/blob/a2971e450331330c98c5ca0c109563f684d60f60/py7zr/py7zr.py#L458-L467

**Comment by miurahr** [comment]
Try to implement in #136 
Could you test it and give me a feedback?

**Comment by myers** [comment]
This looks good to me!
