### ISSUE TITLE
Possible python 3.5 issue with 0.7?

### ISSUE THREAD

**Issue by jurplel** [miurahr/py7zr#151]
https://github.com/jurplel/install-qt-action/issues/42

**Comment by miurahr** [comment]
It has already drop CI test of python3.5 with 0.7.
An issue reported is a syntax which is introduced in python 3.6.

**Comment by miurahr** [comment]
Fix released as v0.7.4

**Comment by jurplel** [comment]
Awesome, thanks!

**Comment by miurahr** [comment]
Also fixed in master branch and released as v0.8.0b3
