### ISSUE TITLE
decompression get wrong: no output data.

### ISSUE THREAD

**Issue by zhbzhbzhbz** [miurahr/py7zr#178]
**Describe the bug**
decompression get wrong: no output data.

**To Reproduce**
1. run command in terminal："py7zr x 1593750358075c++obf7.7z"
2. See error: decompression get wrong: no output data.

**Environment:**
 - OS: Windows 10
 - Python 3.8
 - py7zr version: 0.7.4

**Test data(please attach in the report):**
The file url：http://qcw2817j7.bkt.gdipper.com/1593750358075c%2B%2Bobf7.7z
(No virus)

**Additional context**
1. When I use 7z client(https://www.7-zip.org) or winrar, I can correctly decompress this file.
2. I can use your library to decompress other .7z files I have.

Thank you~

**Comment by miurahr** [comment]
A data is compressed by LZMA+BCJ

**Comment by miurahr** [comment]
This may be a bug in Python Standard library lzma because following test code become fail.
```
def test_lzma_raw_decompressor_lzmabcj():
    filters = []
    filters.append({'id': lzma.FILTER_X86})
    filters.append(lzma._decode_filter_properties(lzma.FILTER_LZMA1, b']\x00\x00\x01\x00'))
    decompressor = lzma.LZMADecompressor(format=lzma.FORMAT_RAW, filters=filters)
    with testdata_path.joinpath('lzmabcj_3.7z').open('rb') as infile:
        infile.read(32)
        out = decompressor.decompress(infile.read(11327))
    assert len(out) == 12800
```
where a test data is 'lzmabcj_3.lzma' which can be obtained by gunzip attached file.

A test data is a payload  distilled from @zhbzhbzhbz reported test data.
It skips first 32 bytes and get 11372 bytes.

A data size is come from following 7z command output

```
   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2019-08-02 21:17:32 ....A        12800        11327  c++obf7.exe
------------------- ----- ------------ ------------  --------
```
[lzmabcj_3.7z.gz](https://github.com/miurahr/py7zr/files/4870442/lzmabcj_3.7z.gz)

**Comment by miurahr** [comment]
But it run well that skip BCJ filter.
BCJ filter is a 1:1 filter that input and output size is same.

```
def test_lzma_raw_decompressor_lzmabcj():
    filters = []
    # XXX #  filters.append({'id': lzma.FILTER_X86})
    filters.append(lzma._decode_filter_properties(lzma.FILTER_LZMA1, b']\x00\x00\x01\x00'))
    decompressor = lzma.LZMADecompressor(format=lzma.FORMAT_RAW, filters=filters)
    with testdata_path.joinpath('lzmabcj_3.7z').open('rb') as infile:
        infile.read(32)
        out = decompressor.decompress(infile.read(11327))
    assert len(out) == 12800
```

This result show us a bug may be exist in BCJ filter in python's lzma library.

**Comment by miurahr** [comment]
I've tested it with Python 3.8.3 and Python 3.6.9[pypy-7.3.1-alpha] on Mint Linux.

**Comment by miurahr** [comment]
Python lzma module is thin wrapper of liblzma.

I can reproduce this with following C program which use liblzma

```
///////////////////////////////////////////////////////////////////////////////
//
/// \file       test_bcj_exact_size2.c
/// \brief      Tests LZMA+BCJ decoding
///
//
//  Author:     Hiroshi Miura
//
//  This file has been put into the public domain.
//  You can do whatever you want with this file.
//
///////////////////////////////////////////////////////////////////////////////

#include "tests.h"


static uint8_t buf[12800];
static uint8_t obuf[12800];


static void
decompress(size_t in_size)
{
    lzma_ret lzret;

    const size_t out_size = 12800;
    lzma_stream strm = LZMA_STREAM_INIT;
    strm.next_in = buf;
    strm.avail_in = in_size;
    strm.next_out = obuf;
    strm.avail_out = out_size;

	lzma_options_lzma opt_lzma;
	succeed(lzma_lzma_preset(&opt_lzma, 0));

	lzma_filter filters[3] = {
		{ .id = LZMA_FILTER_X86, .options = NULL },
		{ .id = LZMA_FILTER_LZMA1, .options = &opt_lzma },
		{ .id = LZMA_VLI_UNKNOWN, .options = NULL },
	};

    succeed(lzma_raw_decoder(&strm, filters));

    lzret = lzma_code(&strm, LZMA_RUN);
    if (lzret == LZMA_STREAM_END) {
        expect(strm.total_in == in_size);
        expect(strm.total_out == out_size);
        lzma_end(&strm);
        return;
    }
    expect(lzret == LZMA_OK);
    expect(strm.total_in == in_size);
    expect(strm.total_out == 12796);  // this should be 12800 == out_size
    expect(strm.total_out == out_size);
}


extern int
main(void)
{
    FILE * filp = fopen("lzmabcj.bin", "rb");
    int in_size = fread(buf, sizeof(uint8_t), 11327, filp);
	decompress(in_size);
	return 0;
}
```
[lzmabcj.bin.gz](https://github.com/miurahr/py7zr/files/4872155/lzmabcj.bin.gz)

**Comment by miurahr** [comment]
reported to xz-devel mailing list https://www.mail-archive.com/xz-devel@tukaani.org/msg00370.html

**Comment by zhbzhbzhbz** [comment]
> reported to xz-devel mailing list https://www.mail-archive.com/xz-devel@tukaani.org/msg00370.html

Wow! Really admire your nice work!! Thanks~

**Comment by zhbzhbzhbz** [comment]
> reported to xz-devel mailing list https://www.mail-archive.com/xz-devel@tukaani.org/msg00370.html

What's more, I found that although the error decompression get wrong: no output data occured, the compressed files inside the .7z archive were correctly extracted~

**Comment by miurahr** [comment]
I think it is not correctly extracted, last 4 bytes of 0x00 is lacking, and permission,  attributes, and timestamps are not correct, because permissions is set after extracting data, which is aborted.

**Comment by miurahr** [comment]
Report to Python devel community: [BPO-41210](https://bugs.python.org/issue41210)  and Ma Lin  (@animalize) trying reproduce and confirmed. 
We will wait a progress in  xz-devel.

**Comment by miurahr** [comment]
#198 and #199 implement alternative BCJ filters and use it for LZMA1+BCJ(X86, PPC, ARM, ARMT, SPARC).

**Comment by miurahr** [comment]
A discussion on xz-devel resulted that it is **not a bug**, and we should not use it with LZMA1+BCJ. we can use FORMAT_ALONE or implement BCJ by our own.
