### ISSUE TITLE
Will the extraction of multi-volume files be supported in future?

### ISSUE THREAD

**Issue by zhbzhbzhbz** [miurahr/py7zr#197]
For example, .7z.001, .7z.002

**Comment by miurahr** [comment]
You can do it 

```
$ cat 7z.* >  7z.7z
```

**Comment by zhbzhbzhbz** [comment]
> You can do it or same things on python.
> 
> ```
> $ cat a.7z.001 a.7z.002 >  a.7z
> $ py7zr x a.7z
> ```

Thanks~ But regarding different platforms, this may be better:
```
filenames  = ['example.7z.001', 'example.7z.002']
with open('result.7z', 'ab') as outfile:  # append in binary mode
    for fname in filenames:
        with open(fname, 'rb') as infile:        # open in binary mode also
            outfile.write(infile.read())
```

**Comment by zhbzhbzhbz** [comment]
And I just spent an hour to spread your library on Stackoverflow and written an introduction for py7zr on my blog~ 
Only 34 stars for such a useful library ......

**Comment by miurahr** [comment]
@zhbzhbzhbz thank you for answering many question around 7zip and python on stackoverflow! 
It is my first impression and motivation I cannot find any answer that is smart python way on SO.

IMHO, creating 7z file from multi-volume file chunks  is not optimal way. If each volumes has a multiple of Giga Bytes,
user need to make a temporary file that may be a multiple 10GB file.
It produce unnecessary I/O and total performance can be bad,

Here is an idea to resolve the situation.

py7zr.SevenZipFile(file) accept a file object that can 'seek' and 'read(size)'. for example

```
with open('something.7z', 'rb') as szfile:
    with py7zr.SevenZipFile(szfile, 'r') as archive:
        archive.extactall()
```

so if you can make a class which has a method 'seek()' and 'read()',  and open() that accept  a list of files ['a.7z.001' 'a.7z.002'] ,
py7zr virtually traverse it and extract.
The opposite is also worth. Current implementation of multi-volume is that create a single archive at first, and split it into files.
If you can make a class which has a method 'seek()' and 'write()' and open() with a list of files, it brings great values.

**Comment by miurahr** [comment]
#243 is an experimental implementation of multi-volume wrapper class.
You are encouraged to extend it to become a generic class to provide all the functions RawIOBase, then it realize multi-volume functions for any applications.

**Comment by miurahr** [comment]
You are welcome to [Multi Volume file wrapper project](https://github.com/miurahr/multivolume) to realize  [my comment](https://github.com/miurahr/py7zr/issues/197#issuecomment-662865901)

You may be able to handle multi-volume using it 

```
import multivolumefile
import py7zr

with multivolumefile.open(['archive.7z.001', 'archive.7z.002'], mode='rb') as mvf:
    with py7zr.SevenZipFile(mvf, 'r') as archive:
        archive.extractall()
```

I've add it as a test case in #243.

**Comment by miurahr** [comment]
Now explanation is added to document;
https://py7zr.readthedocs.io/en/latest/user_guide.html#extraction-from-multi-volume-archive
