### ISSUE TITLE
Twofish cipher for encryption and decryption with private keys

### ISSUE THREAD

**Issue by Kavan72** [miurahr/py7zr#200]
i found some game zip file with Twofish encryption. it's good if support Twofish cipher. if you need one exmple then i can give u. i've it on c++

**Comment by miurahr** [comment]
Could you provide sample 7z file? Because of github restriction, please zip it and upload here.

**Comment by Kavan72** [comment]
here is one file link :- http://www.filedropper.com/gamescriptscx64 
here is c source code :- http://www.filedropper.com/warfaceunpak2

**Comment by miurahr** [comment]
Cannot download your link.

```
/tmp$ LANG=C wget http://www.filedropper.com/gamescriptscx64
--2020-07-23 14:40:20--  http://www.filedropper.com/gamescriptscx64
Resolving www.filedropper.com (www.filedropper.com)... 144.76.226.41
Connecting to www.filedropper.com (www.filedropper.com)|144.76.226.41|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.filedropper.com/gamescriptscx64 [following]
--2020-07-23 14:40:20--  https://www.filedropper.com/gamescriptscx64
Connecting to www.filedropper.com (www.filedropper.com)|144.76.226.41|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-07-23 14:40:22 ERROR 404: Not Found.
```

Please upload from here 
![upload-select-bar](https://docs.github.com/assets/images/help/pull_requests/select-bar.png)

**Comment by Kavan72** [comment]
[GameScriptsC_x64.zip](https://github.com/miurahr/py7zr/files/4964187/GameScriptsC_x64.zip)
[Warface_Unpak.zip](https://github.com/miurahr/py7zr/files/4964190/Warface_Unpak.zip)

**Comment by miurahr** [comment]
Cannot retrieve .7z file from uploaded zip file.
```
unzip GameScriptsC_x64.zip 
Archive:  GameScriptsC_x64.zip

warning [GameScriptsC_x64.zip]:  zipfile claims to be last disk of a multi-part archive;
  attempting to process anyway, assuming all parts have been concatenated
  together in order.  Expect "errors" and warnings...true multi-part support
  doesn't exist yet (coming soon).
error [GameScriptsC_x64.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```

**Comment by Kavan72** [comment]
No, this is encrypted zip file with Twofish cipher. the source code is a method to decrypt zip file

**Comment by miurahr** [comment]
py7zr is a library to handle 7zip files,  not zip (pkzip and its variant) files.

And,  IMO, your sample file is also not valid zip file because its header is starts with

 **00 8f 31 ce** 95 7a 59 e4 d1 be 2c db b5 82 4d 03

against the zip file should start from **b"PK\x03\x04"**

Spec -> https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT
