### ISSUE TITLE
Consider adding "need_password()" function?

### ISSUE THREAD

**Issue by zhbzhbzhbz** [miurahr/py7zr#208]
In the newest release of another archive library, **rarfile**, the author added a useful function "need_password()"
https://rarfile.readthedocs.io/api.html#rarfile.RarFile.needs_password
I don't know whether it will be a lot of work~

**Comment by miurahr** [comment]
7-zip has a specification that  encrypt a header. That is why SevenZipFile() class ask password that can used to open header of archive.

It is impossible to provide need_password() in that case.

**Comment by zhbzhbzhbz** [comment]
> 7-zip has a specification that encrypt a header. That is why SevenZipFile() class ask password that can used to open header of archive.
> 
> It is impossible to provide need_password() in that case.

thanks~ I see

**Comment by freddrake** [comment]
When attempting to open a 7-zip file with an encrypted header, I get the following exception if I don't provide the password:

~~~~~~ text
Traceback (most recent call last):
  ...
    zf = py7zr.SevenZipFile(bytesio, mode='r')
  File ".../py7zr/py7zr.py", line 345, in __init__
    raise e
  File ".../py7zr/py7zr.py", line 318, in __init__
    self._real_get_contents(password)
  File ".../py7zr/py7zr.py", line 373, in _real_get_contents
    header = Header.retrieve(self.fp, buffer, self.afterheader, password)
  File ".../py7zr/archiveinfo.py", line 850, in retrieve
    obj._read(fp, buffer, start_pos, password)
  File ".../py7zr/archiveinfo.py", line 883, in _read
    decompressor = folder.get_decompressor(compressed_size)
  File ".../py7zr/archiveinfo.py", line 390, in get_decompressor
    self.decompressor = SevenZipDecompressor(self.coders, packsize, self.unpacksizes, self.crc, self.password)
  File ".../py7zr/compressor.py", line 743, in __init__
    self.cchain.add_filter(get_alternative_decompressor(coders[i], unpacksizes[i], password))
  File ".../py7zr/compressor.py", line 600, in get_alternative_decompressor
    return algorithm_class_map[filter_id][1](coder['properties'], password)
  File ".../py7zr/compressor.py", line 168, in __init__
    key = calculate_key(password.encode('utf-16LE'), numcyclespower, salt, 'sha256')
AttributeError: 'NoneType' object has no attribute 'encode'
~~~~~~

When no password is provided, would it be reasonable to raise `py7zr.PasswordRequired` here?

**Comment by miurahr** [comment]
@freddrake Thank you for the report, and it seems another issue than here.
I've raised #234 as delegate of you.

**Comment by miurahr** [comment]
#235 try to implement needs_password() when header is not encrypted and payload is, it returns True.

**Comment by miurahr** [comment]
v0.10.0a6 prelease published.
