### ISSUE TITLE
use max_length argument for raw LZMA1 data 

### ISSUE THREAD

**Issue by animalize** [miurahr/py7zr#210]
Lasse Collin said:

> If you use lzma_raw_decoder() for end-markerless LZMA1, make sure that
> you never give it more output space than the real uncompressed size. **In
> rare cases** this could result in extra output or an error since the
> decoder would try to decode more output using the input it has gotten
> so far. Overall I think the hack with lzma_alone_decoder() is a better
> way with the current API.

The [`LZMADecompressor.decompress(data, max_length=-1)`](https://docs.python.org/3/library/lzma.html#lzma.LZMADecompressor.decompress) function has a `max_length` parameter since Python 3.5.

It seems the `max_length` should be set to the output size when decomressing a raw LZMA1 data.

**Comment by animalize** [comment]
IMO only set this argument for raw LZMA1 data.

For raw LZMA2 data, if not set this argument, it has a chance to check whether `actual_output_size == recorded_size`

**Comment by miurahr** [comment]
Thank you for suggestions. Now it is implemented.
