### ISSUE TITLE
Compatibility with numpy fromfile

### ISSUE THREAD

**Issue by rspadim** [miurahr/py7zr#221]
The idea of this Issue is create a compatible object to use with numpy fromfile function

the object of py7zr should have an "readinto" attribute, from numpy source:
https://github.com/numpy/numpy/blob/0311c93c8c43cd913303c529673d69575901475e/numpy/core/records.py#L913

**Comment by miurahr** [comment]
@rspadim Could you provide test case and test data for the use case? As always, Pull-Request is welcome.
