### ISSUE TITLE
API reporting need for a password

### ISSUE THREAD

**Issue by freddrake** [miurahr/py7zr#231]
It would be good to be able to determine whether an archive or entry requires a password to extract, without having to attempt extraction.

I'm not sure if the 7-zip format supports separate control of encryption for individual files, but I'd appreciate and API that allows me to ask if a password is required on the appropriate unit, whether that's the whole file (either on **SevenZipFile** or the **ArchiveInfo**), or for individual entries (on the **FileInfo**).

The [**rarfile** library](https://rarfile.readthedocs.io/) provides a **needs_password()** method on **RarFile**; something similar would be useful.

**Comment by miurahr** [comment]
Duplicated with #208
