### ISSUE TITLE
SevenZipFile.Test() return None for read 7zip files

### ISSUE THREAD

**Issue by girardbaptiste** [miurahr/py7zr#233]
[fichier2.zip](https://github.com/miurahr/py7zr/files/5202715/fichier2.zip) (created with 7zip 19-00 (x64) on windows 10)

**Describe the bug**
After openning an existing zip archive and use the test() function, it returns None instead of True or False.
This is due to the crc of the files contains in the 7zip file : 
 - When the header created (in SevenZipFile.__init__()) is retrived, the crcs are put in self.header.main_streams.substreamsinfo.digests
 - When test() starts, it loads the crc from self.header.main_streams.packinfo.crcs but it has not been initialised.

**Related issue**
/

**To Reproduce**
1. Prepare test data attached as 'file' in current directory.
2. Run following code with python3.
'
import py7zr
archive = py7zr.SevenZipFile(fichier2.7z')
archive.test()
3. It returns None

**Expected behavior**
It retrurns True

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python 3.8.3
 - py7zr version: 0.9.5

**Test data(please attach in the report):**
See attached 7zip file

**Comment by miurahr** [comment]
Let's see archive data.

Here is a specification of 7zip data format.
https://py7zr.readthedocs.io/en/latest/archive_format.html

test data giving:
```
$ od -A x -t x1  fichier2.7z 
000000 37 7a bc af 27 1c 00 04 a8 a6 47 21 15 00 00 00
000010 00 00 00 00 62 00 00 00 00 00 00 00 da 1f e2 18
000020 01 00 10 43 6f 6e 74 65 6e 75 20 66 69 63 68 69
000030 65 72 20 32 00 01 04 06 00 01 09 15 00 07 0b 01
000040 00 01 21 21 01 00 0c 11 00 08 0a 01 62 2c 59 12
000050 00 00 05 01 19 0c 00 00 00 00 00 00 00 00 00 00
000060 00 00 11 1b 00 66 00 69 00 63 00 68 00 69 00 65
000070 00 72 00 32 00 2e 00 74 00 78 00 74 00 00 00 19
000080 00 14 0a 01 00 94 8d 57 29 dc 85 d6 01 15 06 01
000090 00 20 00 00 00 00 00
000097
```

> 000000 37 7a bc af 27 1c 00 04 a8 a6 47 21 **15 00 00 00**

Header offset is  0x20 + 0x15 = 0x35

Header data is
```
000030 ...................................         01 09 15 00 07 0b 01
000040 00 01 21 21 01 00 0c 11 00 08 0a 01 62 2c 59 12
000050 00 00 05 01 19 0c  ... (continues)
```
- compressed data size(0x09) = 0x15 = 21 bytes
- compression method(0x0b000121) = 0x21  = LZMA2
- unpacksize(0x0c) = 0x11  = 17 bytes
- substreaminfo( 0x08)

....(cont..)

**Comment by miurahr** [comment]
The archive you provide  has a CRC of unpacked streams (= uncompressed files), but does not have a digest of packed streams(=compressed data).

a method test() check a CRC of packed streams, and returns  True / False / None
 - True =  archive's CRC definition and CRC calculation is same
 - False = archive's CRC definition and CRC calculation is not same
 - None = archive don't have CRC definition

So return value (None) is no problem in the case.
