### ISSUE TITLE
Add an API for making multiple volumes

### ISSUE THREAD

**Issue by jack1142** [miurahr/py7zr#236]
**Is your feature request related to a problem? Please describe.**
The cli interface of py7zr allows to create multi-volume archives with specified size. Would it be possible to also allow this through an API?

**Describe the solution you'd like**
While I don't have a specific idea in mind on how I would want this to be done, I would really want it to support file-like objects, so that it could for example be used with BytesIO objects. Maybe that would require the API to be passed with some factory that will return it file-like object when it needs *another* volume? I'm not sure whether that's the best way, but anything that would allow me to make a multi-volume archive in-memory would be great. I guess that it might also need to be done in a way, that doesn't require it to have all volumes in-memory at once, so that this could stil work with bigger file sizes, but I don't know whether it's possible to create split volumes one by one. I would still be happy either way, but I'm guessing it's something that might need to be considered.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by miurahr** [comment]
You can extend #243 to support write, then you can support multi-volume creation.
As usual, Pull-Request is welcome.

When you complete implementation, it may allow you to write like
```
with multivolume.open('file.7z', 'wb', chunk_size="65536") as mv:
   with py7zr.SevenZipFile(mv, 'w') as arc:
      arc.writeall(target)
```

**Comment by miurahr** [comment]
I don't want to add API about multi-volume on py7zr.SevenZipFile. You can make wrapper like #243 then you can realize it.
It is because I implement it as CLI logic not class method.

**Comment by miurahr** [comment]
Now explanation is added to document; 
https://py7zr.readthedocs.io/en/latest/user_guide.html#extraction-from-multi-volume-archive
