### ISSUE TITLE
Extract one small file from a big zip takes a huge time

### ISSUE THREAD

**Issue by xVanTuring** [miurahr/py7zr#239]
**Describe the bug**
I have a zip file about 85.8MB, which contains a big file 218MB(unziped) and a small file 37.1KB(unziped). 
I use `archive.extract(unzip_dir, targets=[name])` to extact the small file to `unzip_dir`. It takes about 4s.
I dig into the code, and find it was caused by these lines.
https://github.com/miurahr/py7zr/blob/2433c8418de26516d659932ff271b22f46db561d/py7zr/py7zr.py#L1040-L1056
the `elif` block will decompress file and spend time even if the file is not wanted.

**My Code**
```python
name = None
for file_name in allfiles:
    if file_name.endswith("xml"):
        name = file_name
        sbsar_xml_path = os.path.join(unzip_dir, file_name)
print("Unzip {}".format(name))
archive.extract(unzip_dir, targets=[name])
print("Done! {}s".format((datetime.datetime.now() - start).total_seconds()))

```

**Expected behavior**
It should be quite fast.

**Environment (please complete the following information):**
 - OS: Windows
 - Python 3.7
 - py7zr version: 0.9.7

**Test data(please attach in the report):**
It's too big to upload, but any zip with one big file and a small file should work.

**Comment by xVanTuring** [comment]
To be clear, 
Here is an example zip file information
```
[xvan@xvan-wk test-zip]$ 7za l test.7z 

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,24 CPUs AMD Ryzen 9 3900X 12-Core Processor             (870F10),ASM,AES-NI)

Scanning the drive for archives:
1 file, 87887274 bytes (84 MiB)

Listing archive: test.7z

--
Path = test.7z
Type = 7z
Physical Size = 87887274
Headers Size = 193
Method = LZMA2:24 BCJ
Solid = -
Blocks = 2

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2020-07-23 07:00:04 ....A         5589         2219  blender.desktop
2020-08-31 19:57:36 ....A    238919088     87884862  blender
------------------- ----- ------------ ------------  ------------------------
2020-08-31 19:57:36          238924677     87887081  2 files
```
Following 7za command `7za x ./test.7z *.desktop` takes less than a second.

Following Python code takes more than 4 seconds
``` python
import py7zr
import datetime

start = datetime.datetime.now()
file_path = "/workspace/Documents/test-zip/test.7z"
archive = py7zr.SevenZipFile(file_path, mode='r')
allfiles = archive.getnames()
name = None
for file_name in allfiles:
    if file_name.endswith("desktop"):
        name = file_name
archive.extract("/workspace/Documents/test-zip", targets=[name])
print("Takes {} s".format((datetime.datetime.now() - start).total_seconds()))
```

**Comment by xVanTuring** [comment]
More information:
I also created a 7z file from gnome-nautilus and try to use 7za to unzip the desktop file. And it takes a lot of time. Here is the detail of the zip file:
```
7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,24 CPUs AMD Ryzen 9 3900X 12-Core Processor             (870F10),ASM,AES-NI)

Scanning the drive for archives:
1 file, 89382677 bytes (86 MiB)

Listing archive: ./test_binary.7z

--
Path = ./test_binary.7z
Type = 7z
Physical Size = 89382677
Headers Size = 222
Method = LZMA:23
Solid = +
Blocks = 1

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2020-08-31 19:57:36 ....A    238919088     89382455  blender
2020-07-23 07:00:04 ....A         5589               blender.desktop
------------------- ----- ------------ ------------  ------------------------
2020-08-31 19:57:36          238924677     89382455  2 files
```
I notice the `blocks` are different from the previous one, I'm not quite familiar with compression algorithms. But I guess: if we want to unzip a file and we can ignore all the other unrelated blocks. So I tried a small change, it will filter unwanted blocks(folder) and I ran a `tox` test, looks like it passed the tests.(I' not familiar with tox too...):
```python
                    for i in range(numfolders):
                        # Filter folder's files before sending to thread
                        wanted_block = False
                        for f in folders[i].files:
                            fileish = self.target_filepath.get(f.id, None)
                            if fileish is not None:
                                wanted_block = True
                        if not wanted_block:
                            continue
                        p = threading.Thread(target=self.extract_single,
                                             args=(filename, folders[i].files,
                                                   self.src_start + positions[i], self.src_start + positions[i + 1],
                                                   q, exc_q))
                        p.start()
                        extract_threads.append(p)
```

**Comment by nmz787** [comment]
4 seconds hardly seems like a "huge time" to me. 4x longer also seems reasonable for a pure-Python library, 7zip is probably coded in C or C++. I'm assuming py7zr doesn't depend on an installed copy of the 7zip program to function (I haven't confirmed this though).

**Comment by xVanTuring** [comment]
@nmz787 
Well if it's about unzipping whole archive, then it's fine, The native 7z is not faster than py7zr. 
How ever it's about unzipping a small file, and as far as I can tell pyz7r wastes time on unwanted files, it will decompress it to `NullIO()` which is `/dev/null`.
Also in the third post, I find that the unzipping unwanted is needed when two files are gouped in one `block`, and the native 7z will also takes about 4s to unzip only the small file. here is the shell output
```
[xvan@xvan-wk test-zip]$ time 7z x test_binary.7z *.desktop

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,12 CPUs AMD Ryzen 9 3900X 12-Core Processor             (870F10),ASM,AES-NI)

Scanning the drive for archives:
1 file, 89382677 bytes (86 MiB)

Extracting archive: test_binary.7z
--
Path = test_binary.7z
Type = 7z
Physical Size = 89382677
Headers Size = 222
Method = LZMA:23
Solid = +
Blocks = 1

Everything is Ok

Files: 2
Size:       238924677
Compressed: 89382677

real	0m3.659s
user	0m3.637s
sys	0m0.011s
```

**Comment by miurahr** [comment]
py7zr decompress archive by threading for each block(py7zr.archiveinfo.Folder class).
If you can find a way to decide whether  block can skip whole or not before starting thread, it should improve performance. 

Here is a place to start thread.

https://github.com/miurahr/py7zr/blob/master/py7zr/py7zr.py#L1010

**Comment by miurahr** [comment]
@xVanTuring  does #239 improve your case?

**Comment by xVanTuring** [comment]
@miurahr Yes, it does make improvements. It takes only `0.001852s` to unzip the small file now. Great!

**Comment by miurahr** [comment]
v0.10.0b1 released.

**Comment by HoshinoKoji** [comment]
It seems that unnecessary operations are still being performed. I have a huge **uncompressed** 7z file (150GB) consisting of 130,000 small files (1MB). It takes over 30 seconds even if I try to read a single file, which is terrible.
