### ISSUE TITLE
Providing a write function that can take for input what is return by read

### ISSUE THREAD

**Issue by girardbaptiste** [miurahr/py7zr#248]
**Is your feature request related to a problem? Please describe.**
When passing from files provided by the operating system, the write / writeall function do well. But when the files comes from an IO stream, the API is not adapted.

**Describe the solution you'd like**
When you create an archive, the input files could be files provided by the OS but they should be also files in memory.
For exemple using the output of readall() to create an other archive with a subset.

**Describe alternatives you've considered**
When I want to pass files from an achive to another, I need to unzip files on the hard drive and then make a new archive.
When I want to add stream into an achive, I store them on hard drive an then I create the archive.

**Comment by miurahr** [comment]
What design of API can provide such a functionality? Iterator? provide writestr?

**Comment by miurahr** [comment]
Now we have and implement following methods;

* readall() -> Dict[str, IO]
* read(targets: List[str]) -> Dict[str, IO]

* extractall(path, callback)
* extract(path, targets: List[str])

* writeall(path, arcname)
* write(file, arcname)
* writestr(data, arcname)

What is a missing piece?

**Comment by miurahr** [comment]
There is another point to consider. 
read() and readall() returns BytesIO() objects. It cause memory footprint for extracted data.
It may be better to return some iterator  that generate metadata and data, and the extraction will be done when iterated object called.

One idea is such that user can call like

```
for arcname, f in SevenZipFileObj.readf():
    with open(arcname, 'w') as target:
        for data in f.read():  # <- extraction happened here.
             target.write(data) 
```

By this direction, we can consider `write` family method such as

```
with open(arcname, 'rb') as f:
     SevenZipFileObj.writef(f, arcname)
f = io.BytesIO(data)
SevenZipFileObj.writef(f, arcname)
```

Then
```
with SevenZipFile(source, 'r') as source:
    with SevenZipFile(name, 'w') as target: 
        for arcname, f in souce.readf():
            target.writef(f, arcname)   # <- extraction and compression happened here on the fly.
```

Is it a design @girardbaptiste considered?

**Comment by miurahr** [comment]
Now #290 introduce `writebio(bio: BinaryIO, size: int, arcname:str)` method

**Comment by girardbaptiste** [comment]
"with SevenZipFile(source, 'r') as source:
    with SevenZipFile(name, 'w') as target: 
        for arcname, f in souce.readf():
            target.writef(f, arcname)   # <- extraction and compression happened here on the fly.
"
is fine. We can now extract and reconstruct a new acrhive and add filters to the file list.

I had undestood that 7z read and write is better when you read the entire 7zip file. Are the performances better when the files are writen one by one or all together.

**Comment by miurahr** [comment]
I have a design issue for the implementation .
Because 7zip takes `solid` archive strategy, and py7zr uses multi-threading extraction of archives, it is difficult to provide one by one iteration, that requires completely different extraction strategy.

Is it acceptable for you to use the combination of   `read()` and `writef()` as such

```
with SevenZipFile(source, 'r') as source:
    data_dict = source.readall()
with SevenZipFile(name, 'w') as target:
    for arcname, bio in data_dict:
        if does_it_write(arcname):
            target.writef(bio, arcname)
```

**Comment by girardbaptiste** [comment]
Thas was the point of my last comment. As I undestand the module, for reading a single file inside the 7z you need to read the entire 7z. This solution seems a good compromise.

You can also do 

```
with SevenZipFile(source, 'r') as source:
    data_dict = source.readall()

selected_data = does_it_write(data_dict)  # same type as data_dict
with SevenZipFile(name, 'w') as target:
   target.write_data_dict(selected_data)
```

This provide a way to py7zr to do what it wants with all the files.

**Comment by miurahr** [comment]
#302 introduce writed() that is write_data_dict method.

**Comment by miurahr** [comment]
The feature is released.
