### ISSUE TITLE
Some archive LZMA+BCJ cause CRC32 error.

### ISSUE THREAD

**Issue by miurahr** [miurahr/py7zr#249]
**Describe the bug**
Some archive  compressed with LZMA+BCJ cause CRC32 error.
Reported at https://github.com/miurahr/aqtinstall/issues/162

**Related issue**
(if exist)

**To Reproduce**

Extract a file
https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt5_56/qt.56.win64_msvc2015_64/5.6.2-0icu-win-msvc2013-Windows8.1-x64.7z

**Expected behavior**
run without CRC32 error.

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu Linux 18.04.01] Mint Linux 20
 - Python [e.g. 3.6, pypy3.6.9-7.3.0] 3.8.2
 - py7zr version: [e.g. v0.5b1, commit #123456 on master] 1499b83d1e92 on  master

**Test data(please attach in the report):**
Link above

**Additional context**
An issue is reported at aqtinstall project.

**Comment by miurahr** [comment]
The archive which produce the issue has a strange  properties.
It has a definition of coder  No.0 as BCJ and No.1 as LZMA.
Ordinal archive has No.0 as LZMA and No.1. as BCJ.

Filters should be ordered for pipeline. It is reversed, and it seems to be a behavior against wrong archive parameter.

**Comment by miurahr** [comment]
When hack to ignore BCJ filter in chain even specified, it works for the case....

**Comment by animalize** [comment]
If the CRC32 verification fails after BCJ decoding, it could back to verify the CRC32 of decompressed data. For correct file, no overhead will be added.

**Comment by miurahr** [comment]
As I commented, there is only one place to be changed by BCJ filter, that causes error.
https://github.com/miurahr/py7zr/pull/250#issuecomment-699568354

**Comment by miurahr** [comment]
I recognized the behavior and wrong part now by comparison with an observation of debugger on https://github.com/miurahr/simple-liblzma-build

**Comment by miurahr** [comment]
The fix is pushed

**Comment by miurahr** [comment]
Fix released as v0.9.9 and v0.10.0b3.
