### ISSUE TITLE
Is there a way to know if the extraction has completed?

### ISSUE THREAD

**Issue by pidugusundeep** [miurahr/py7zr#265]
By using this method
```
with py7zr.SevenZipFile("Archive.7z", 'r') as archive:
    archive.wxtractall(path="/tmp")
```
 is there a way to know if the extraction has completed and invoke a process after extraction?

**Comment by miurahr** [comment]
You can check callback feature which is called before and after extracting each archived files.
Usage is here.
https://github.com/miurahr/py7zr/blob/master/py7zr/cli.py#L303

**Comment by miurahr** [comment]
There is no feedback in 30 days.
