### ISSUE TITLE
'NoneType' object has no attribute 'encode' when creating encrypted header archive with password

### ISSUE THREAD

**Issue by h4sh5** [miurahr/py7zr#278]
I'm trying to create a password encrypted archive with encrypted headers like so:

```py
with py7zr.SevenZipFile(outpath, mode='w', password="test123") as archive:
        archive.set_encrypted_header(True)
        archive.writeall(filepath, arcname=os.path.basename(filepath))
```
and it throws me this error 

```
lib/python3.8/site-packages/py7zr/compressor.py", line 96, in __init__
    key = calculate_key(password.encode('utf-16LE'), self.cycles, self.salt, 'sha256')
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by h4sh5** [comment]
My guess is that when the encrypted header is being written the password was not passed to the header, therefore `password` is None (thus the NoneType object).

Another possibility would be the file that was being written does not have the password - I added print() debugging above that line (line 96) and the first time it printed the password but not the second time.

Can you fix that please?

**Comment by miurahr** [comment]
#280 will fix this.

**Comment by h4sh5** [comment]
Thank you so much <3
