### ISSUE TITLE
Method to extract to memory instead of file

### ISSUE THREAD

**Issue by medoc92** [miurahr/py7zr#283]
Hi, 

As stated in a pylzma issue, it would be useful to have methods to extract data from an archive member to memory, instead of creating files. To replace pylzma getmember().read() and such.

**Comment by miurahr** [comment]
You can use a memory interface of SevenZipFile().read() and .readall() like
```
with SevenZipFile('archive.7z', 'r') as zip:
    for fname, bio in zip.readall().items():
        print('{:s}: {:X}...'.format(name, bio.read(10))
```

Please be consulted at https://py7zr.readthedocs.io/en/latest/api.html#sevenzipfile-object

**Comment by medoc92** [comment]
Thanks ! I should have read the doc instead of just the github page.

py7zr now replaces pylzma as  7z archive processor of choice in Recoll: https://www.lesbonscomptes.com/recoll/pages/features.html#sevenz

May I suggest that an example of in memory processing on the githb page might be useful though ? People who want to extract to the filesystem already have the option of using a command line program.
