### ISSUE TITLE
WARNING: Test data issue_218.7z and issue_218_2.7z contains a Blackmoon trojan designed for steel user credentials !!!

### ISSUE THREAD

**Issue by balazik** [miurahr/py7zr#285]
**Describe the bug**
The file tests/data/issue_218_2.7z contains a trojan ( Blackmoon also known as KRBanker) designed to steel user credentials!

**To Reproduce**
1. carefully unpack tests/data/issue_218_2.7z
2. make a antvirus scan on extracted a2002ToolBox.
3. You will see that dll 窗口SPY.dll and a2002ToolBox.exe contain the trojan.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python 3.6
 - py7zr version: e.g. v0.11.1, commit c006d7eaaed56a3df0fcf06102295cc65fcc53bc on master

**Comment by miurahr** [comment]
The file is included in v0.9.5, in Aug, 2020.

**Comment by miurahr** [comment]
The files `窗口SPY.dll and a2002ToolBox.exe ` are in issue_218.7z not issue_218_2.7z.

**Comment by miurahr** [comment]
ClamAV don't find krbanker trojan but it found a malware in issue_218_2.7z 

```
$ clamscan -ri .
issue_218_2.7z: Win.Malware.Confidence-6629254-0 FOUND
HP酷表.exe: Win.Malware.Confidence-6629254-0 FOUND
hp酷表扩展.dll: Win.Malware.Gotango-7000352-0 FOUND

----------- SCAN SUMMARY -----------
Known viruses: 8877566
Engine version: 0.102.4
Scanned directories: 43
Scanned files: 847
Infected files: 3
Data scanned: 114.00 MB
Data read: 87.79 MB (ratio 1.30:1)
Time: 69.183 sec (1 m 9 s)
```

**Comment by miurahr** [comment]
The file issue_218.7z is in master branch and two pull request threads.
The file issue_218_2.7z is only in one pull request thread.
I need to remove affected file from history of master branch.
And also I need to ask a github support to remove commit referred by sha hash on the pull request.

https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

**Comment by miurahr** [comment]
Thank you for report! @balazik 

I've now rewirte a git history for master and release branches.

**Comment by eli-schwartz** [comment]
It's generally not considered great to rewrite history and I somehow doubt there is a practical danger to users in having such a file buried in past history.

**Comment by balazik** [comment]
Sorry for the confusion with the file name. The correct file name is "issue_218.7z".

@eli-schwartz is right. There is no high risk if you keep the history as is. Just remove it from newest release and everything should be fine. 

I see you have already done so, now should be everything ok. Thanks.

Closing the issue.

**Comment by RollingStar** [comment]
Why was this test data included in the first place?

**Comment by miurahr** [comment]
It cannot be removed by git command. Github keeps it but there is not in repository.
