### ISSUE TITLE
append data into existed 7z raise AttributeError exception

### ISSUE THREAD

**Issue by huaiweicheng** [miurahr/py7zr#287]
**Describe the bug**
append data into existed 7z raise AttributeError exception

**To Reproduce**

1. touch 2 txts.
2. Run following code with python3.

```
import py7zr
with py7zr.SevenZipFile("a.7z", 'a') as archive:
    archive.write("1.txt")
with py7zr.SevenZipFile("a.7z", 'a') as archive:
    archive.write("2.txt")

```

or just use py7zr cli
![image](https://user-images.githubusercontent.com/4011117/105274136-8573ff00-5bd7-11eb-9f28-045d34706125.png)
3. See error

**Expected behavior**
append 2.txt into existed a.7z normally

**Environment (please complete the following information):**
 - OS:  Windows 10, Linux 
 - Python 3.8.2
 - py7zr version: 0.11.3

**Comment by miurahr** [comment]
You should run when 'a.7z' does not exists.

```
import py7zr
with py7zr.SevenZipFile("a.7z", 'w') as archive:
    archive.write("1.txt")
with py7zr.SevenZipFile("a.7z", 'a') as archive:
    archive.write("2.txt")
```

**Comment by huaiweicheng** [comment]
Yeah, it's my mistake that the first mode should be 'w'.

And Could you figure out what's happening? many thanks.

**Comment by miurahr** [comment]
There are files that size is zero, so `unpacksizes` array is not exist, but try to add.
When some of target file has data, it create `unpacksizes`  header field when mode='w'.

**Comment by miurahr** [comment]
Fix PR https://github.com/miurahr/py7zr/pull/288

**Comment by huaiweicheng** [comment]
@miurahr   I think the problem may not be the empty file. I reproduce the same problem.

**Comment by huaiweicheng** [comment]
Hi @miurahr  is there any progress?

**Comment by miurahr** [comment]
does #288 work for you?

**Comment by huaiweicheng** [comment]
Yeah. I've tested it and it worked!   Thank you so much~

**Comment by miurahr** [comment]
v0.12.0 out.
