### ISSUE TITLE
[Question] With block, close(), AssertionError

### ISSUE THREAD

**Issue by DJManas** [miurahr/py7zr#317]
Hello,

I like this library and I am using it to test volumes and some extra stuff and I want to ask one thing. If I use with, do stuff and call close() I get assert error. Should I call close with the with code block?

I mean something like this
```
with SevenZipFile(fileName) as sZipFile:
  for fname, bio in sZipFile.readall().items():
    internalFileName = fname
    internalHash = countHash(file=bio)        
  sZipFile.close()
```

I get something like:
```
  File "/usr/local/lib/python3.9/site-packages/py7zr/py7zr.py", line 348, in __exit__
    self.close()
  File "/usr/local/lib/python3.9/site-packages/py7zr/py7zr.py", line 973, in close
    self._fpclose()
  File "/usr/local/lib/python3.9/site-packages/py7zr/py7zr.py", line 351, in _fpclose
    assert self._fileRefCnt > 0
```

So my question do I have to call the close or does it release resources when leaving the function I am using it in?
Thanks,
Regards,
Petr Sourek

**Comment by miurahr** [comment]
You do double close.

```
with SevenZipFile(fileName) as sZipFile:
  for fname, bio in sZipFile.readall().items():
    internalFileName = fname
    internalHash = countHash(file=bio)
```

This works and it releases a resource when leaving `with` block.

**Comment by DJManas** [comment]
Thank you.
