### ISSUE TITLE
Problematic unit test 

### ISSUE THREAD

**Issue by animalize** [miurahr/py7zr#321]
If the zstd library changes the compression algorithm, the assertion may fail. 

For example, a few days ago, zstd added support for SIMD instructions (SSE2/NEON), then the compressed data is likely to have some changes.

Other compression algorithms have not been updated for many years, so it may be okay. But zstd is still under active development, this way may not work.

```python
@pytest.mark.unit
def test_pyzstd_compressor_1():
    plain_data = b"\x00*\x1a\t'd\x19\xb08s\xca\x8b\x13 \xaf:\x1b\x8d\x97\xf8|#M\xe9\xe1W\xd4\xe4\x97BB\xd2"
    compressor = py7zr.compressor.ZstdCompressor(level=3)
    outdata = compressor.compress(plain_data)
    outdata = compressor.compress(plain_data)
    outdata += compressor.flush()
    compressed = (
        b"\x28\xb5\x2f\xfd"
        b"\x00XE\x01\x00\x04\x02\x00*\x1a\t'd\x19\xb08s\xca\x8b\x13 \xaf:\x1b\x8d\x97\xf8|#M\xe9\xe1W\xd4"
        b"\xe4\x97BB\xd2\x01\x00\x18\xb8z\x02"
    )
    assert outdata == compressed
```
https://github.com/miurahr/py7zr/blob/master/tests/test_extra_codecs.py#L84-L96

**Comment by miurahr** [comment]
I'd like remove the test case.

**Comment by animalize** [comment]
I close this issue.
