### ISSUE TITLE
Folders in archive are created empty on disk despite in memory read mode

### ISSUE THREAD

**Issue by fra-luc** [miurahr/py7zr#323]
**Describe the bug**
When calling `readall()` with `mode = 'r'`  on a in-memory 7zip file that contains some _folders_ , such folders are created, _empty_, on disk.

**Related issue**
(if exist)

**To Reproduce**
1. Prepare a test 7zip file with a folder structure and files inside.
2. Run the following code with python3.
```python
def handle_7zip(content: bytes):
    _7zip = SevenZipFile(io.BytesIO(content), mode='r')
    for fname, file_content in _7zip.readall().items():
        # do something
    _7zip.close()

handle_7zip(content) # call with bytes argument
```
3. empty folders following the folder structure in the archive are created on disk

**Expected behavior**
I'd expect nothing is written to disk since I want to perform all processing in memory.

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 20.04.02
 - Python version: 3.7.9
 - py7zr version: 0.15.1

**Test data(please attach in the report):**
A minimum test data to reproduce your problem.

**Additional context**

**Comment by miurahr** [comment]
@Zoynels any ideas?
