### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by dimapu** [miurahr/py7zr#326]
**Describe the bug**
Wrong syntax in the example code.

**To Reproduce**
1. Go to the page https://py7zr.readthedocs.io/en/stable/api.html#sevenzipfile-object
2. The several lines with `targets = [f if filter_pattern.match(f) for f in allfiles]` raise syntax error.

**Expected behavior**

The code should look like `targets = [f for f in allfiles if filter_pattern.match(f)]`

**Environment (please complete the following information):**
Documentations pages for versions latest, stable, and 0.15.1 contain this typo.

**Additional context**
Thanks for creating and supporting this package. Let me know if you would like me to submit a PR.

**Comment by miurahr** [comment]
@dimapu thank you for the report. As usual, Pull-Request is welcome.

**Comment by miurahr** [comment]
Fix commited.
