### ISSUE TITLE
TypeError: argument must be read-only bytes-like object, not memoryview when trying to decrypt file served by BytesIO

### ISSUE THREAD

**Issue by marlemion** [miurahr/py7zr#328]
Hi,

I am trying to decrypt data from a bytesIO file object. It is working fine for an unencrypted file, but not for an encrypted file.

The resulting error is:

```
Traceback (most recent call last):
  File "./test1.py", line 73, in <module>
    k_dms.kopano_extract_zip(attachment, passwords=['password'])
  File "/home/eger/winpat/k_dms/kopano_utils.py", line 189, in kopano_extract_zip
    szip_data = szip_file.readall()
  File "/usr/local/lib/python3.8/site-packages/py7zr/py7zr.py", line 922, in readall
    return self._extract(path=None, return_dict=True)
  File "/usr/local/lib/python3.8/site-packages/py7zr/py7zr.py", line 592, in _extract
    self.worker.extract(
  File "/usr/local/lib/python3.8/site-packages/py7zr/py7zr.py", line 1147, in extract
    self.extract_single(
  File "/usr/local/lib/python3.8/site-packages/py7zr/py7zr.py", line 1258, in extract_single
    raise e
  File "/usr/local/lib/python3.8/site-packages/py7zr/py7zr.py", line 1243, in extract_single
    crc32 = self.decompress(fp, f.folder, ofp, f.uncompressed, f.compressed, src_end)
  File "/usr/local/lib/python3.8/site-packages/py7zr/py7zr.py", line 1295, in decompress
    tmp = decompressor.decompress(fp, out_remaining)
  File "/usr/local/lib/python3.8/site-packages/py7zr/compressor.py", line 598, in decompress
    tmp = self._decompress(data, max_length)
  File "/usr/local/lib/python3.8/site-packages/py7zr/compressor.py", line 567, in _decompress
    data = decompressor.decompress(data)
  File "/usr/local/lib/python3.8/site-packages/py7zr/compressor.py", line 206, in decompress
    temp = self.cipher.decrypt(self.buf.view)
  File "/usr/lib/python3.8/site-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
TypeError: argument must be read-only bytes-like object, not memoryview
```
The respective snippet of code is:
```
            try:
                with py7zr.SevenZipFile(io.BytesIO(attachment.data), password=password) as szip_file:
                   szip_data = szip_file.readall()
                szip_default_password = password
                break
            except py7zr.exceptions.PasswordRequired:
                pass
```
The 7z file has been created using the 7z File Manager on Windows:

![image](https://user-images.githubusercontent.com/5897656/115669498-9fdd8600-a348-11eb-8351-5e473190031c.png)

It is sent per Mail and retrieved as an attachment from the MAPI object (kopano server). Hence, the data should be fine, if the file is fine.

Can you help me further or did byte me a bug?

Thanks!

**Comment by miurahr** [comment]
When adding following test code, it works well. Any additional conditions for reproduce?

```
@pytest.mark.files
def test_extract_encrypted_1_frommem(tmp_path):
    archive = py7zr.SevenZipFile(io.BytesIO(testdata_path.joinpath("encrypted_1.7z").read_bytes()), password="secret")
    _dict = archive.readall()
    archive.close()
```

**Comment by miurahr** [comment]
The error was claimed in a file `Cipher/blockalgo.py` that was removed in 6 years ago at pycryptodome project.

What pycryptodome version do @marlemion use?

```
  File "/usr/lib/python3.8/site-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
TypeError: argument must be read-only bytes-like object, not memoryview
```

**Comment by miurahr** [comment]
I can reproduced a similar issue on pycryptodome 3.5.1, and 3.6.6 works well.

**Comment by miurahr** [comment]
From changelog in pycryptodome;

https://www.pycryptodome.org/en/latest/src/changelog.html#id45

### 3.6.0 (8 April 2018)

#### New features
* Introduced export_key and deprecated exportKey for DSA and RSA key objects.
* Ciphers and hash functions **accept memoryview objects in input.**
* Added support for SHA-512/224 and SHA-512/256.

**Comment by marlemion** [comment]
Hello, thanks for your fast reply.

I am on cygwin and apparently, I do not use pycryptodome at all. It is at least not installed in the system.

It appears that I am using Crypto in version 2.6.1

Do I need to install pycryptodome?

**Comment by miurahr** [comment]
Here is a requirements

https://github.com/miurahr/py7zr/blob/b7c6adcd55860d924d1d082952d1f071ffc530ff/setup.cfg#L35-L47

**Comment by miurahr** [comment]
Question answered.

**Comment by miurahr** [comment]
Change dependency to **PyCryptodomex** will avoid the case.
**PyCryptodome** has same package path with **PyCrypto** for convenience to replacement.
The questioned confliction  can be avoided by #334

**Comment by miurahr** [comment]
fix merged.
