### ISSUE TITLE
Issues with archiving with password

### ISSUE THREAD

**Issue by parvezmahmud** [miurahr/py7zr#330]
Can't archive files/folders with password

Run:  `py7zr c -P target_file.7z target_dir`
Output: `
      usage: py7zr [-h] [--version] {l,x,c,a,t,i} ...
      py7zr: error: unrecognized arguments: -P
`

**Comment by miurahr** [comment]
There is no implementation of CLI to support compression with password.

**Comment by Urahara** [comment]
This is closed here: #332 right?

**Comment by miurahr** [comment]
yes, you are right.

**Comment by parvezmahmud** [comment]
Thank you so much for working on that issue so fast
