### ISSUE TITLE
Compress two identical files

### ISSUE THREAD

**Issue by qlc-89** [miurahr/py7zr#339]
Compress two identical files， Both files are compressed， I think it is reasonable to delete the old files and compress the new ones

Environment： Windows 10,   Linux 

versions：0.12.0，  0.14.0

**Comment by qlc-89** [comment]
"""test code"""

import py7zr
import os

seven_zip_path = 'D:/data'
file_path = 'D:/'

for i in range(2):
	if not os.path.exists(seven_zip_path):
	    os.mkdir(seven_zip_path)
	if not os.path.exists(os.path.join(seven_zip_path, 'a.7z')):
	    with py7zr.SevenZipFile(os.path.join(seven_zip_path, 'a.7z'), 'w') as archive:
	        archive.write(os.path.join(file_path, '1.txt'), arcname='1.txt')
	else:
	    with py7zr.SevenZipFile(os.path.join(seven_zip_path, 'a.7z'), 'a') as archive:
	        archive.write(os.path.join(file_path, '1.txt'), arcname='1.txt')
![image](https://user-images.githubusercontent.com/66470618/119425992-f882b300-bd3a-11eb-946d-66752ba2e0f7.png)

**Comment by miurahr** [comment]
It works as intended.
