### ISSUE TITLE
Cannot use relative path when compressing and change the out dir when decompressing 

### ISSUE THREAD

**Issue by yinchuandong** [miurahr/py7zr#345]
**Describe the bug**
When I compress a file, it only allows to use absolute path. Otherwise, even if the compressing is successful, the decompressing is not working.

**To Reproduce**
1. Prepare a test file
2. Run following code with python3.

```python
import py7zr
input_filepath = "../../test_data/users.csv"
output_filepath = "../../users.7z"

with py7zr.SevenZipFile(output_filepath, "w") as z:
    # z.write(input_filepath)
    z.writeall(input_filepath)
```

3. users.7z is produced
4. the following code to de-compress
```python
with py7zr.SevenZipFile(output_filepath, mode="r") as z:
    print(z.getnames())
    z.extractall("./extract-all/")
```
5. See error
![image](https://user-images.githubusercontent.com/3993196/126100384-320d750d-f2b1-43b5-91f4-60e2c5d5444b.png)

**Expected behavior**
Not matter if I specify absolute path or relative path for input file, the ideal behaviour is to maintain another separate folder structure. When I tried to decompress, I can specify any output file path.

**Environment (please complete the following information):**
 - OS: Mac OS big sur
 - Python 3.8
 - py7zr version: 0.16.1

**Comment by miurahr** [comment]
Why not just
```
import py7zr
input_filepath = "test_data/users.csv"
output_filepath = "users.7z"

os.chdir("../../")
with py7zr.SevenZipFile(output_filepath, "w") as z:
    z.writeall(input_filepath)
```

**Comment by miurahr** [comment]
Can another 7-zip command extract the produced archive file? 

For example, when you have p7zip from home brew

```
cd /tmp
7z x users.7z
```
