### ISSUE TITLE
Use with XMLtoDict Streaming

### ISSUE THREAD

**Issue by karrtikiyerkcm** [miurahr/py7zr#346]
**Is your feature request related to a problem? Please describe.**
I have a large 7z file which is nothing but stackoverflow posts XML dump. I would like read this XML file using XMLtoDict streaming.

**Describe the solution you'd like**
https://github.com/martinblech/xmltodict
>>> def handle_artist(_, artist):
...     print(artist['name'])
...     return True
>>> 
>>> xmltodict.parse(GzipFile('discogs_artists.xml.gz'),
...     item_depth=2, item_callback=handle_artist)
A Perfect Circle
Fantômas
King Crimson
Chris Potter
...

**Describe alternatives you've considered**
converting 7z to tar or gzip formats but wasn't straightforward.

**Additional context**
NA

**Comment by miurahr** [comment]
What interface standard or specification py7zr can  support to realize it?

**Comment by karrtikiyerkcm** [comment]
Unfortunately I do not enough about xmltodict, I have raised a similar question here: https://github.com/martinblech/xmltodict/issues/275
It might be good if you can ask your question on this post so that author of xmltodict can answer.

**Comment by karrtikiyerkcm** [comment]
Bases on the below documentation of GZipFile which works with XmltoDict, it must be `io.BufferedIOBase interface` interface which needs to be supported.
https://docs.python.org/3/library/gzip.html

```class gzip.GzipFile(filename=None, mode=None, compresslevel=9, fileobj=None, mtime=None)
Constructor for the GzipFile class, which simulates most of the methods of a file object, with the exception of the truncate() method. At least one of fileobj and filename must be given a non-trivial value.

The new class instance is based on fileobj, which can be a regular file, an io.BytesIO object, or any other object which simulates a file. It defaults to None, in which case filename is opened to provide a file object.

When fileobj is not None, the filename argument is only used to be included in the gzip file header, which may include the original filename of the uncompressed file. It defaults to the filename of fileobj, if discernible; otherwise, it defaults to the empty string, and in this case the original filename is not included in the header.

The mode argument can be any of 'r', 'rb', 'a', 'ab', 'w', 'wb', 'x', or 'xb', depending on whether the file will be read or written. The default is the mode of fileobj if discernible; otherwise, the default is 'rb'. In future Python releases the mode of fileobj will not be used. It is better to always specify mode for writing.

Note that the file is always opened in binary mode. To open a compressed file in text mode, use open() (or wrap your GzipFile with an io.TextIOWrapper).

The compresslevel argument is an integer from 0 to 9 controlling the level of compression; 1 is fastest and produces the least compression, and 9 is slowest and produces the most compression. 0 is no compression. The default is 9.

The mtime argument is an optional numeric timestamp to be written to the last modification time field in the stream when compressing. It should only be provided in compression mode. If omitted or None, the current time is used. See the mtime attribute for more details.

Calling a GzipFile object’s close() method does not close fileobj, since you might wish to append more material after the compressed data. This also allows you to pass an io.BytesIO object opened for writing as fileobj, and retrieve the resulting memory buffer using the io.BytesIO object’s getvalue() method.

GzipFile supports the io.BufferedIOBase interface, including iteration and the with statement. Only the truncate() method isn’t implemented.

GzipFile also provides the following method and attribute:```

**Comment by miurahr** [comment]
You can use `readall()` or `read()` method to get `io.ByteIO` objects from `py7zr`
docs : https://py7zr.readthedocs.io/en/latest/api.html#py7zr.SevenZipFile.readall

Here is a sample code from the document.
```
with SevenZipFile('archive.7z', 'r') as zip:
    for fname, bio in zip.readall().items():
        print('{:s}: {:X}...'.format(fname, bio.read(10))
```
`readall()` returns `dict` of filename and `io.ByteIO` object. `items()` method iterate dictionary in for loop.

Please be careful that it consume memory as same size as uncompressed data, because you said "I have a large 7z file "

**Comment by karrtikiyerkcm** [comment]
@miurahr : thanks, in the code above you have mentioned `bio.read(10)`, how did we arrive at this value 10? How do we decide on it?

**Comment by miurahr** [comment]
>  in the code above you have mentioned bio.read(10), how did we arrive at this value 10? How do we decide on it?

Example code just print first 10 bytes in hex. otherwise, `bio.read()` will fulfill your terminal screen with hex characters.

**Comment by karrtikiyerkcm** [comment]
Thanks, but it is unclear to me as to how I can decide the correct size to read while passing to XmltoDict.

**Comment by miurahr** [comment]
`bio` in example source is an object of `io.BytesIO` which is implementation of `io.BufferedIOBase interface`.
https://docs.python.org/3/library/io.html#io.BytesIO

You said
> it must be io.BufferedIOBase interface which needs to be supported.

That it is.

When you have the function that accept io.BufferdIOBase interface `the_function_accept_BufferedIOBase()`

```
with SevenZipFile('archive.7z', 'r') as zip:
    for fname, bio in zip.readall().items():
        the_function_accept_BufferedIOBase(bio)
```

might work.

**Comment by miurahr** [comment]
No feedback.
