### ISSUE TITLE
some files (.dll/.exe) won't extract

### ISSUE THREAD

**Issue by ReenigneArcher** [miurahr/py7zr#348]
**Describe the bug**
I am attempting to extract a 7z archive, but it fails returning the exception for `UnsupportedCompressionMethodError`.

**Related issue**
(if exist)

**To Reproduce**
1. Using this file from RetroArch: https://buildbot.libretro.com/stable/1.9.7/windows/x86_64/RetroArch.7z
2. Run following code with python3.
```python
import py7zr
archive_file = 'RetroArch.7z'
destination_folder = 'some_folder'
with py7zr.SevenZipFile(archive_file, 'r') as archive:
    archive.extractall(path=destination_folder)
```
3. roughly 2000 files extracted
4. Receive exception `UnsupportedCompressionMethodError`

Alternatively I tried to use a loop to extract the files (takes incredibly long amount of time)
```python
import py7zr
archive_file = 'RetroArch.7z'
destination_folder = 'some_folder'
with py7zr.SevenZipFile(archive_file, 'r') as archive:
    file_list = archive.getnames()

for file in file_list:
    with py7zr.SevenZipFile(archive_file, 'r') as archive:
        try:
            archive.extract(path=destination_folder, targets=file)
        except py7zr.exceptions.UnsupportedCompressionMethodError as e:
            print('File: %s :: Error: %s' % (file, e))
        except py7zr.exceptions.CrcError as e:
            print('File: %s :: Error: %s' % (file, e))
        except py7zr.exceptions.Bad7zFile as e:
            print('File: %s :: Error: %s' % (file, e))
        except py7zr.exceptions.ArchiveError as e:
            print('File: %s :: Error: %s' % (file, e))
        except py7zr.exceptions.InternalError as e:
            print('File: %s :: Error: %s' % (file, e))
        except Exception as e:
            print('File: %s :: Error: %s' % (file, e))
```

**Expected behavior**
* Entire archive should extract.
* Exception message should include a list of files that fail along with what the compression method is that is unsupported (if possible)

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu Linux 18.04.01] Win10
 - Python [e.g. 3.6, pypy3.6.9-7.3.0] Python 3.9.6
 - py7zr version: [e.g. v0.5b1, commit #123456 on master] 0.16.1

**Test data(please attach in the report):**
I don't know what this means, but everything needed to reproduce the issue is listed above.

**Additional context**
All of the files that fail are `.dll` or `.exe` and exist in the primary folder of the archive. I am not an expert on 7z archives but it seems unusual that almost of the files extract without any issue, but these all fail. Is it even possible to have different compression on different files of the same archive? I did read the [compression methods](https://py7zr.readthedocs.io/en/latest/api.html#compression-methods) from the documentation but it was not clear to me.

How could I see what type of compression is used on an archive (or file within an archive) to verify?

If py7zr is not capable of this,.. Do you know of any python libraries that are capable of extracting this file?

**Comment by miurahr** [comment]
```
$7z l RetroArch.7z | head -20

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=ja_JP.UTF-8,Utf16=on,HugeFiles=on,64 bits,16 CPUs AM
D Ryzen 7 PRO 4750U with Radeon Graphics (860F01),ASM,AES-NI)

Scanning the drive for archives:
1 file, 171263550 bytes (164 MiB)

Listing archive: RetroArch.7z

--
Path = RetroArch.7z
Type = 7z
Physical Size = 171263550
Headers Size = 107195
Method = LZMA2:26 LZMA:20 BCJ2
Solid = +
Blocks = 2

```

Method is LZMA2, LZMA and BCJ2
BCJ2 is not supported.

**Comment by miurahr** [comment]
The command `py7zr l RetroArch.7z` should also show a similar output.

**Comment by ReenigneArcher** [comment]
Okay, thank you for the fast reply. Do you know of any way to extract this entire file in python?

**Comment by miurahr** [comment]
> Do you know of any way to extract this entire file in python?

* install 7zip executable from https://7-zip.org

``` 
        command_args = ["c:/Program\ files/7-zip/7z.exe", "x", "-aoa", "-bd", "-y", archive]
        try:
            proc = subprocess.run(command_args, check=True)
        except subprocess.CalledProcessError as cpe:
            # error handling
            pass
```

**Comment by miurahr** [comment]
> is there anyway to get the compression method from python directly 

```
with py7zr.SevenZipFile(archive, "r") as arc:
    info = arc.archiveinfo()
    print(info.method_names)
```
https://py7zr.readthedocs.io/en/latest/api.html#py7zr.SevenZipFile.archiveinfo

**Comment by ReenigneArcher** [comment]
Thank you for the information.

I think I have tried every archive library I can find to try and extract this and not having any luck with any of them. I was hoping to avoid including 7z.exe with my application, but I don't see any other option at this point. Even went as far as asking the developer of the archive to change the compression method, but seems unlikely they will.

What would it take to get BCJ2 support in this library? From my understanding this compression is only for windows files (dlls, and exes). Can you utilize the `7z.dll` somehow? Or maybe `archiveint.dll` from `C:\Windows\System32` folder?

**Comment by miurahr** [comment]
> Even went as far as asking the developer of the archive to change the compression method, but seems unlikely they will.

You can see 7-zip manual which compression level uses which algorithms.
https://sevenzip.osdn.jp/chm/cmdline/switches/method.htm#SevenZipX

Only a highest level uses BCJ2

> What would it take to get BCJ2 support in this library? 

When someone support BCJ2 in liblzma library, which is used by Python3.
https://github.com/COMBINE-lab/xz/blob/master/doc/faq.txt#L114


> Q:  I cannot find BCJ and BCJ2 filters. Don't they exist in liblzma?
>
> A:  BCJ filter is called "x86" in liblzma. BCJ2 is not included,
>    because it requires using more than one encoded output stream.
>    A streamable version of BCJ2-style filtering is planned.

**Comment by ReenigneArcher** [comment]
> A streamable version of BCJ2-style filtering is planned.
This was committed to the FAQ on Oct 2, 2010. Doesn't seem promising they will add it any time soon.

I did find another similar project to this one `pylzma` which has references to BCJ2 in the code, but couldn't get it to work either. Seems as though it's no longer maintained.
https://github.com/fancycode/pylzma/blob/master/py7zlib.py

**Comment by miurahr** [comment]
pylzma is a (unmaintained?) project to bind a LZMA SDK to python. LZMA SDK is a part of 7-zip project.

py7zr is a project to extract 7zip container format using Python standard lzma module, which use liblzma under the hood of python.  liblzma is a project to implement lzma/lzma2/bcj algorithms in XZ project.

**Comment by miurahr** [comment]
No further question.
