### ISSUE TITLE
-P (password) option is missing in usage information's / but exist in code

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [miurahr/py7zr#355]
https://github.com/miurahr/py7zr/blob/f579fc67ea77c12052083034254a3ced341e5412/py7zr/cli.py#L117

I am using `0.16.1` (`py7zr.cli Version 0.16.1 : Copyright (C) 2019-2021 Hiroshi Miura (Python 3.9.4 [CPython MSC v.1928 64 bit (AMD64)])`) on Win10 installed via `py -3 -m pip install -U py7zip`).

The password option is missing in the usage information's

```
>py7zr --help
usage: py7zr [-h] [--version] {l,x,c,a,t,i} ...

py7zr

optional arguments:
  -h, --help     show this help message and exit
  --version      Show version

subcommands:
  {l,x,c,a,t,i}  <Commands>
                   c : Create archive with files
                   i : Show information about supported formats
                   l : List contents of archive
                   t : Test integrity of archive
                   x : eXtract files with full paths
```

But looking into your repository and especially in the 0.16.1 tagged version the option should show up in the usage information's. It is in the code.

What went wrong? Or what do I missunderstand?

**Comment by miurahr** [comment]
Could you try to see sub command help?
```
py7zr x --help
```

`--password` is a sub command option, not generic option.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Yes this works then.

Maybe you should think about a re-design here. Maybe I am not usual but as a user I expect "all" help infos when using `-h`, `--help` or `-?`.

If you do not want to show all informations at once I would suggest to add this
`
{l,x,c,a,t,i} -h, --help    show help for subcommands`
```

...
optional arguments:
  -h, --help                  show this help message and exit
  {l,x,c,a,t,i} -h, --help    show help for subcommands`
  --version                   Show version
...
```

btw: There is a typo. The `s` in `show`  should always be uppercase like it is with `--version`.

**Comment by miurahr** [comment]
These help messages are produced by python standard argparse library.
I don't want to reinvent it.

If anyone know how to customize it such like @Codeberg-AsGithubAlternative-buhtz suggested, please tell me.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I looked around in the argparse Issue tracker.

I do not think they will implement it. So I would suggest to close this issue as not-py7zr-related.
