### ISSUE TITLE
Bump py7zr dependency to 0.15.0 ?

### ISSUE THREAD

**Issue by jeanmonet** [miurahr/py7zr#357]
**Describe the bug**
When latest version is installed (0.16.1), pip issues the following warning if I upgrade pyzstd:

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> py7zr 0.16.1 requires pyzstd<0.15.0,>=0.14.4, but you have pyzstd 0.15.0 which is incompatible.

Should pyzstd dependency be bumped to 0.15.0?

Looks safe:

https://github.com/animalize/pyzstd

> 0.15.0 (May 18, 2021)
>     Update zstd source code from v1.4.9 to v1.5.0.
>     Some improvements, no API changes.

**Comment by miurahr** [comment]
Is it feasible to remove an upper limit and change to `pyzstd>=0.14.4`  ?
