### ISSUE TITLE
Expanded input for writeall.

### ISSUE THREAD

**Issue by Symbiomatrix** [miurahr/py7zr#362]
I've forked a small modification to SevenZipFile.writeall and SevenZipFile._writeall so as to enable flattening the zip and picking specific files (eg through glob). It could probably do with some refinement.
@miurahr, penny for your thoughts?

**Comment by miurahr** [comment]
We can add a flag to change behavior.

**Comment by miurahr** [comment]
You are welcome to give us PR as same as other improvements.
