### ISSUE TITLE
Delete file from archive

### ISSUE THREAD

**Issue by jonaslb** [miurahr/py7zr#363]
**Is your feature request related to a problem? Please describe.**
The 7z program has the `d` functionality to remove a file from an archive. As far as I can see from the py7zr docs, this is missing in py7zr.

**Describe the solution you'd like**
A `SevenZipFile.delete(arcname)` method to remove a file from an archive.

**Describe alternatives you've considered**
Using subprocess to call the 7z program is a workaround. But I don't like it so much.

**Comment by buhtz** [comment]
Please deactivate the github-actions bot. The issue is relevant no matter of is activity here or not.
