### ISSUE TITLE
how can I add comment to archive file

### ISSUE THREAD

**Issue by ANXIETIER** [miurahr/py7zr#376]
I read doc and find a PROPERTY named COMMENT, I supposed that can  add comment to archive file, but I didnt get ways to do that

**Comment by miurahr** [comment]
It has not been implemented yet because I don't know a details of specification.

**Comment by miurahr** [comment]
There is no actual implementation in 7-zip/p7zip, so I'd like to remove item from doc.

**Comment by miurahr** [comment]
https://sourceforge.net/p/sevenzip/discussion/45797/thread/9c392b34/

Is this forum thread right for 7-zip's comment feature?
