### ISSUE TITLE
Win32 File namespace convention doesn't work on Cygwin

### ISSUE THREAD

**Issue by soerenwolfers** [miurahr/py7zr#380]
https://github.com/miurahr/py7zr/blob/a880637801e5b0b2d77450104efb2115a47e458c/py7zr/py7zr.py#L558

This hack causes

 ```
FileNotFoundError: [WinError 3] The system cannot find the path specified: '\\\\?\\\\my.company.filesystem\\directory\\'
```
on
```
 fileish.parent.mkdir(parents=True, exist_ok=True)
```
for me. Running Cygwin on Windows 10 and Python 3.6.

**Comment by miurahr** [comment]
`\\?\` is a windows win32 file namespace convention. 

https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#win32-file-namespaces

> For file I/O, the `"\\?\"` prefix to a path string tells the Windows APIs to disable all string parsing and to send the string that follows it straight to the file system. For example, if the file system supports large paths and file names, you can exceed the MAX_PATH limits that are otherwise enforced by the Windows APIs. For more information about the normal maximum path limitation, see the previous section Maximum Path Length Limitation.

Does not cygwin support win32 file namespace?

**Comment by miurahr** [comment]
@soerenwolfers I exclude cygwin  for adding namespace header for windows. Is #381 working for you?

**Comment by soerenwolfers** [comment]
Unfortunately no, `sys.platform=="win32"` for me in Cygwin.

But also, I just tested this on raw Windows without Cygwin and maybe the question mark doesn't work in conjunction with network paths?
```
>>> pathlib.Path(r'\\some\network\path').stat()
os.stat_result(st_mode=16895, st_ino=562949953444643, st_dev=684487699, st_nlink=1, st_uid=0, st_gid=0, st_size=0, st_atime=1590657050, st_mtime=1590657050, st_ctime=1550317254)
```
works but 
```
>>> pathlib.Path(r'\\?\\\some\network\path').stat()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\pathlib.py", line 1161, in stat
    return self._accessor.stat(self)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '\\\\?\\\\some\network\path'
```
doesn't.

**Comment by soerenwolfers** [comment]
Anyway, if you don't wanna be bothered about this, don't worry about me. As a dirty workaround, I'm currently just changing                        ```
os.name = 'dos'
pathlib.PosixPath._flavour.is_supported = True
```
 before calling into py7zr since I don't need long paths.

**Comment by miurahr** [comment]
Thank you for the hint;

path.is_absolute() returns True when network path... Uhmm.
https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.is_absolute
