### ISSUE TITLE
Callback specified is not a subclass of py7zr.callbacks.ExtractCallback class

### ISSUE THREAD

**Issue by Un-index** [miurahr/py7zr#386]
**Describe the bug**
`Error: Callback specified is not a subclass of py7zr.callbacks.ExtractCallback class`
when attempting to provide a callback to py7zr.SevenZipFile.extractall

**To Reproduce**
1. Prepare any 7z file at all
2. Run following code with python3.

```
import py7zr
class callback( py7zr.callbacks.ExtractCallback):
    def __init__(self):
        pass

with py7zr.SevenZipFile('thing.7z', mode='r') as z:
    z.extractall(None,  callback) # z.extractall(None,  py7zr.callbacks.ExtractCallback.report_end) causes the same error
```

3. error produced: ValueError: Callback specified is not a subclass of py7zr.callbacks.ExtractCallback class

**Expected behavior**
expected the callback to execute while the file is being extracted

**Environment:**
 - OS: [Windows 10]
 - Python [3.10]
 - py7zr version: [v0.17.0]

**Additional context**
I'm trying to extract a 7z archive and display the progress as it is being extracted, for that I need to see the bytes processed, and bytes needed to be processed. If this is not a bug then I apologize for that.
Note: I did notice it says "ExtractCallback class is a concrete class used in CLI.". Does this mean this only works with CLI? If not, then how can I use it to display extraction progress?

**Comment by miurahr** [comment]
Thank you for the report. I can reproduce it on #387

**Comment by miurahr** [comment]
You pass `callback` abstract class name as an argument of method. It is invalid.
You should pass an instance of concrete class that inherit from ExtractCallback abstract class.
A `concrete` means that all abstract methods are implemented.

Please implement these FIVE methods and call with instance.

```
class Callback(ABC):
    """Abstrat base class for progress callbacks."""

    @abstractmethod
    def report_start_preparation(self):
        """report a start of preparation event such as making list of files and looking into its properties."""
        pass  # noqa

    @abstractmethod
    def report_start(self, processing_file_path, processing_bytes):
        """report a start event of specified archive file and its input bytes."""
        pass  # noqa

    @abstractmethod
    def report_end(self, processing_file_path, wrote_bytes):
        """report an end event of specified archive file and its output bytes."""
        pass  # noqa

    @abstractmethod
    def report_warning(self, message):
        """report an warning event with its message"""
        pass  # noqa

    @abstractmethod
    def report_postprocess(self):
        """report a start of post processing event such as set file properties and permissions or creating symlinks."""
        pass  # noqa
```

**Comment by miurahr** [comment]
ref https://docs.python.org/3/library/abc.html

**Comment by miurahr** [comment]
I've pushed an improvement for raising better error message.
Please see #387 for the tests and good example how to use callback feature. @Un-index

**Comment by miurahr** [comment]
Please see tests/test_misc.py#L126 for good example
