### ISSUE TITLE
Unable to create password protected archive

### ISSUE THREAD

**Issue by eangius** [miurahr/py7zr#392]
### Describe the bug
Attempting to create password protected compression as per the API documentation sample code results in a corrupted archive when re-opening. Alternatively customizing the filters argument results in runtime exception.

### To Reproduce
1. The directory to compress contains only tab-separated-value text file(s) of the form:
```tsv
LABEL       TEXT
-1          'It gets me mad' - President acts alone on gun control
-1          The 'War on terror' made us unsafe
 1          Street art campaign brightens refugee camp
 1          Stronger UK services growth bodes well for economy in Q4
...
```
See sample [data.txt](https://github.com/miurahr/py7zr/files/7704824/data.txt)

#### ATTEMPT 1
2. Run the following python3 code:
```python
zipfile = 'test.7z'
base = os.path.basename(zipfile).rsplit('.', 1)[0]

with SevenZipFile(
    zipfile, mode='w', password='secret', filters=None
) as archive:
    archive.writeall('/path/to/orig_dir', base)
```

3. See that `test.7z` is produced
4. Open `test.7z` in macOS & see following error:
<img width="380" alt="corrupted_archive" src="https://user-images.githubusercontent.com/50584378/145838134-94922395-dfde-472f-af9c-0f8921b8db0c.png">

#### ATTEMPT 2
2. Run the following python3 code:
```python
zipfile = 'test.7z'
base = os.path.basename(zipfile).rsplit('.', 1)[0]

with SevenZipFile(
    zipfile, mode='w', password='secret', filters=[
        {'id': FILTER_X86},
        {'id': FILTER_LZMA2, 'preset': PRESET_DEFAULT},
        {'id': FILTER_CRYPTO_AES256_SHA256}
    ]
) as archive:
    archive.writeall('/path/to/orig_dir', base)
```

3. See the following runtime exception:
```txt
Traceback (most recent call last):
  File "utilities/credentials.py", line 65, in utilities.credentials.archive_create
    archive.writeall(filename, base)
  File "/Users/eangius/QuantumhoodAI/core/.venv/lib/python3.8/site-packages/py7zr/py7zr.py", line 983, in writeall
    self._writeall(path, arcname)
  File "/Users/eangius/QuantumhoodAI/core/.venv/lib/python3.8/site-packages/py7zr/py7zr.py", line 696, in _writeall
    self.write(path, arcname)
  File "/Users/eangius/QuantumhoodAI/core/.venv/lib/python3.8/site-packages/py7zr/py7zr.py", line 995, in write
    self.header.initialize()
  File "/Users/eangius/QuantumhoodAI/core/.venv/lib/python3.8/site-packages/py7zr/archiveinfo.py", line 1048, in initialize
    folder.prepare_coderinfo(self.filters)
  File "/Users/eangius/QuantumhoodAI/core/.venv/lib/python3.8/site-packages/py7zr/archiveinfo.py", line 381, in prepare_coderinfo
    self.compressor = SevenZipCompressor(filters=filters, password=self.password)
  File "/Users/eangius/QuantumhoodAI/core/.venv/lib/python3.8/site-packages/py7zr/compressor.py", line 776, in __init__
    raise UnsupportedCompressionMethodError
TypeError: __init__() missing 2 required positional arguments: 'data' and 'message'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 3, in <module>
  File "utilities/credentials.py", line 57, in utilities.credentials.archive_create
    with SevenZipFile(
  File "/Users/eangius/QuantumhoodAI/core/.venv/lib/python3.8/site-packages/py7zr/py7zr.py", line 388, in __exit__
    self.close()
```

### Expected behavior
A `test.7z` archive is produced in the directory of the target folder. Password prompt occurs when archive is opened. If successful credentials, content is unpacked with original content of target folder. Archive is openable in platform independent manner.

**Environment (please complete the following information):**
 - OS: macOS 11.2.3 (untested in other operating-systems)
 - Python: 3.8.7
 - py7zr version: 0.17.0

### Test data(please attach in the report):
A minimum test data to reproduce your problem.

### Additional context
End goal is to LZMA2 compress (at level 9) a collection of big files into a single password protected archive.

**Comment by eangius** [comment]
Thanks for the awesome 🔥 quick turnaround  time. I’ll try it out in the coming days.

**Comment by eangius** [comment]
The encrypt-compress to decrypt-extract cycle now works programmatically for me. Perhaps this is an OS thing, but double clicking on the encrypted-compressed archive to open it errors with dialog shown above rather than prompt for password.

Curiously, I'm not seeing any change in resulting archive size (known to manually compress smaller) when specifying the compression level like this:
```python
with SevenZipFile('test.7z', 'w', filters=[
    {'id': FILTER_X86},
    {'id': FILTER_LZMA2, 'preset': 9},
    {'id': FILTER_CRYPTO_AES256_SHA256}
]) as archive:
   ...
```
@miurahr is my understanding how to config the preset `filters` list correct?

**Comment by miurahr** [comment]
py7zr does not anything against `preset`, and it pass a filters parameter to Python's standard LZMA module like `lzma.LZMACompressor(format=lzma.FORMAT_RAW, filters=filters)` when filter is LZMA2+BCJ(X86).

From python documentation and XZ(libLZMA) documentation, larger preset means using more memory to compress.

This table is my understanding from xz manual.

preset  | dictionary size  | max memory usage
--------  | -------------------   | --------------------
6          |   8MiB               |  94MiB
9          |  64MiB              |  674MiB

There may be little difference when target file is smaller than sizes of parameters.


* https://docs.python.org/3/library/lzma.html#specifying-custom-filter-chains
* https://tukaani.org/xz/xz-javadoc/org/tukaani/xz/LZMA2Options.html
* https://linux.die.net/man/1/xz

**Comment by miurahr** [comment]
I've compared resulted 7z files by test case `test_encrypt_file_8` without preset and preset is 9.

You can see a difference, default has method `LZMA2:23` and the latter has method `LZMA2:26`. 
26 means 64MiB

from https://7zip.bugaco.com/7zip/MANUAL/cmdline/switches/method.htm
> Default values for LZMA are 24 (16 MB) in normal mode, 25 (32 MB) in maximum mode (-mx=7) and 26 (64 MB) in ultra mode (-mx=9). If you do not specify any symbol from the set [b|k|m|g], the dictionary size will be calculated as DictionarySize = 2^Size bytes. 

This might be an evidence. 

##  default

```bash
$ 7z l target.7z 

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=ja_JP.UTF-8,Utf16=on,HugeFiles=on,64 bits,16 CPUs AMD Ryzen 7 PRO 4750U with Radeon Graphics (860F01),ASM,AES-NI)

Scanning the drive for archives:
1 file, 692 bytes (1 KiB)

Listing archive: target.7z

--
Path = target.7z
Type = 7z
Physical Size = 692
Headers Size = 244
Method = LZMA2:23 BCJ 7zAES
Solid = +
Blocks = 1

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2019-03-14 09:10:08 D....            0            0  scripts
2019-03-14 09:10:08 ....A          111          448  scripts/py7zr
2019-03-14 09:07:13 ....A           58               setup.cfg
2019-03-14 09:09:01 ....A          559               setup.py
------------------- ----- ------------ ------------  ------------------------
2019-03-14 09:10:08                728          448  3 files, 1 folders

```

## preset 9

```bash
$ 7z l target.7z 

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=ja_JP.UTF-8,Utf16=on,HugeFiles=on,64 bits,16 CPUs AMD Ryzen 7 PRO 4750U with Radeon Graphics (860F01),ASM,AES-NI)

Scanning the drive for archives:
1 file, 692 bytes (1 KiB)

Listing archive: target.7z

--
Path = target.7z
Type = 7z
Physical Size = 692
Headers Size = 244
Method = LZMA2:26 BCJ 7zAES
Solid = +
Blocks = 1

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2019-03-14 09:10:08 D....            0            0  scripts
2019-03-14 09:10:08 ....A          111          448  scripts/py7zr
2019-03-14 09:07:13 ....A           58               setup.cfg
2019-03-14 09:09:01 ....A          559               setup.py
------------------- ----- ------------ ------------  ------------------------
2019-03-14 09:10:08                728          448  3 files, 1 folders
```

**Comment by MXS2514** [comment]
> I've compared resulted 7z files by test case `test_encrypt_file_8` without preset and preset is 9.
> 
> You can see a difference, default has method `LZMA2:23` and the latter has method `LZMA2:26`. 26 means 64MiB
> 
> from https://7zip.bugaco.com/7zip/MANUAL/cmdline/switches/method.htm
> 
> > Default values for LZMA are 24 (16 MB) in normal mode, 25 (32 MB) in maximum mode (-mx=7) and 26 (64 MB) in ultra mode (-mx=9). If you do not specify any symbol from the set [b|k|m|g], the dictionary size will be calculated as DictionarySize = 2^Size bytes.
> 
> This might be an evidence.
> 
> ## default
> Method = LZMA2:23 BCJ 7zAES
> ## preset 9
> Method = LZMA2:26 BCJ 7zAES

sorry for bumping,
Is that true to say  
[{"id": py7zr.FILTER_LZMA2, "preset": 9}]
is the equvalent setting compression level 9 on gui?
I know there are something with BCJ2 issue, how about cpmpression rate w/o it?
