### ISSUE TITLE
Can't defend against a special path traversal attack

### ISSUE THREAD

**Issue by h-j-13** [miurahr/py7zr#406]
**Is your feature request related to a problem? Please describe.**
Can't defend against a special path traversal attack
when filename like `tmp/../../../../../etc/test.txt`
`py7zr.extractall()` will release the file to the parent directory

I think the reason is this code https://github.com/miurahr/py7zr/blob/master/py7zr/py7zr.py#L535-L539
```python
        for f in self.files:
            # TODO: sanity check
            # check whether f.filename with invalid characters: '../'
            if f.filename.startswith("../"):
                raise Bad7zFile
```

It only handles the case where the filename starts with `../../`
but if filename is `/tmp/../../../../`, it still case a path traversal attack

you can get malicious 7z file from https://github.com/jwilk/traversal-archives 
**Non-leading dot-dot** part

**Describe the solution you'd like**
add more logic about check filename. like below
```python
def compress_file_name_check(dir_path, file_name):
    file_name = file_name.lstrip("./")
    full_path = os.path.join(dir_path, file_name)
    if os.path.commonprefix((os.path.realpath(full_path), dir_path)) != dir_path:
        return None
    else:
        return file_name
```
There is a more detailed discussion thread here, 
https://stackoverflow.com/questions/45188708/how-to-prevent-directory-traversal-attack-from-python-code
https://stackoverflow.com/questions/6803505/does-my-code-prevent-directory-traversal

**Comment by miurahr** [comment]
@h-j-13 does #407 fix the issue? could you review it?

**Comment by h-j-13** [comment]
> @h-j-13 does #407 fix the issue? could you review it?

LGTM 👍

**Comment by miurahr** [comment]
#407 merged.
