### ISSUE TITLE
Failed raising UnsupportedCompressionMethodError as an argument error when trying to extract an unsupported archive in thread extraction mode

### ISSUE THREAD

**Issue by dio-gh** [miurahr/py7zr#431]
**Bug Description:**

Extraction fails midway, despite the same archive extracting fine with regular 7-Zip. The exact error is:
```
TypeError: UnsupportedCompressionMethodError.__init__() missing 1 required positional argument: 'message'
```

**To Reproduce:**

Simply try extracting the file with `py7zr x <filename>`, or via `extractall()`.

**Expected behavior:**

Should complete proper.

**Environment:**
 - OS: Windows 8.1 Pro
 - Python version: 3.10.4
 - py7zr version: latest from pip (0.18.3)

**Test Data:**

Uploading .7z files to GitHub is not supported, but you can retrieve the file directly from [here.](https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-3d31e2f2a9a465c19f2729a937411a1db5f1a15c/rpcs3-v0.0.21-13443-3d31e2f2_win64.7z) It's the archive of the latest build of the emulator called RPCS3.

**Additional context:**

<details>
  <summary>The full traceback...</summary>
  

```
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\py7zr.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\py7zr\__main__.py", line 25, in main
    return cli.Cli().run()
  File "C:\Python310\lib\site-packages\py7zr\cli.py", line 99, in run
    return args.func(args)
  File "C:\Python310\lib\site-packages\py7zr\cli.py", line 358, in run_extract
    a.extractall(callback=cb)
  File "C:\Python310\lib\site-packages\py7zr\py7zr.py", line 975, in extractall
    self._extract(path=path, return_dict=False, callback=callback)
  File "C:\Python310\lib\site-packages\py7zr\py7zr.py", line 633, in _extract
    self.worker.extract(
  File "C:\Python310\lib\site-packages\py7zr\py7zr.py", line 1254, in extract
    raise exc_type(exc_val).with_traceback(exc_tb)
TypeError: UnsupportedCompressionMethodError.__init__() missing 1 required positional argument: 'message'
```
</details>

<details>
  <summary>What I'm trying to accomplish...</summary>

I'm writing a [background updater](https://github.com/dio-gh/rpcs3-bg-updater/) for the aforementioned emulator, and I'm trying to get rid of the [subshelling](https://github.com/dio-gh/rpcs3-bg-updater/blob/2815848ae635338701584798710582e849598dee/updater.py#L24-L30) to 7-Zip, because it's unsafe and not nice. And because I hope to save a few more lines of code... :))
</details>

**Comment by miurahr** [comment]
A file reported is not supported because it compressed with LZMA2+BCJ2 
Duplicated issue with #408, #414

**Comment by miurahr** [comment]
A type error is happened because

When extraction thread raise exception, it catch and push into a queue
at py7zr.py:1281

```python
                exc_tuple = sys.exc_info()
                exc_q.put(exc_tuple)
```

then dequeue it at py7zr:1253 and try raise it 

```python
                        (exc_type, exc_val, exc_tb) = exc_q.get()
                        raise exc_type(exc_val).with_traceback(exc_tb)
```

There may be a code problem.

**Comment by miurahr** [comment]
A fix for TypeError is merged into `master`.

**Comment by dio-gh** [comment]
> A file reported is not supported because it compressed with LZMA2+BCJ2

Ah sorry, I assumed full feature parity with 7-Zip. I'm not that familiar with the intricacies of the format, so those tickets didn't stand out to me.

Thanks for the quick response. Closing.

**Comment by miurahr** [comment]
@dio-gh Thanks for feedback.
Your report pull my head up to investigate  `TypeError` and find a bug on error handler.

Python core library lzma supports LZMA2+BCJ and LZMA+BCJ but not LZMA2+BCJ2 because dependency library liblzma don't support it. py7zr uses python core library or 3rd party libraries for algorithms.
