### ISSUE TITLE
The x86 (32 bit) system installation py7zr reports an error. X64 (64 bit) yes.

### ISSUE THREAD

**Issue by xiezhoubin** [miurahr/py7zr#455]
![image](https://user-images.githubusercontent.com/75734559/172046315-fec0578e-9eee-41f4-95b3-ba8765b86b49.png)

```
PS D:\Projects\PythonProjects\ArduinoPackageInstallation\ArduinoPackageInstallation_V3> pip install py7zr
Processing c:\users\86153\appdata\local\pip\cache\wheels\a7\ce\25\7181dbeffbdb3d6b97a37f02deafdddcaa7ec6d5a5c7b0cabc\py7zr-0.18.9-py3-none-any.whl
Collecting psutil
  Using cached psutil-5.9.1-cp37-cp37m-win32.whl (242 kB)
Collecting pybcj>=0.6.0
  Using cached pybcj-0.6.0-cp37-cp37m-win32.whl (33 kB)
Collecting texttable
  Using cached texttable-1.6.4-py2.py3-none-any.whl (10 kB)
Collecting multivolumefile>=0.2.3
  Using cached multivolumefile-0.2.3-py3-none-any.whl (17 kB)
  copying zipfile_deflate64\_zipfile.py -> build\lib.win32-cpython-37\zipfile_deflate64
  copying zipfile_deflate64\__init__.py -> build\lib.win32-cpython-37\zipfile_deflate64
  running build_ext
  building 'zipfile_deflate64.deflate64' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for zipfile-deflate64
Failed to build zipfile-deflate64
ERROR: Could not build wheels for zipfile-deflate64 which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 20.1.1; however, version 22.1.2 is available.
You should consider upgrading via the 'd:\softwareinstallationpath\python\python3.7.9_x86\python.exe -m pip install --upgrade pip' command.
PS D:\Projects\PythonProjects\ArduinoPackageInstallation\ArduinoPackageInstallation_V3>
```

**Comment by miurahr** [comment]
@cielavenir zipfile-deflate64 become  install error.

**Comment by xiezhoubin** [comment]
> @cielavenir zipfile-deflate64 become  install error. 

I would like to ask what is the latest version that has not been added to "zipfile-deflate64". I'll try to use the old version to see if there are any problems.

**Comment by miurahr** [comment]
@xiezhoubin  You can see a package files of zipfile-deflate64 at https://pypi.org/project/zipfile-deflate64/#files

Because there are no 32bit binaries,  you tried to install it from source. 
It is what your log message said.

```
building 'zipfile_deflate64.deflate64' extension
error: Microsoft Visual C++ 14.0 or greater is required.
```

> **Microsoft Visual C++ 14.0 or greater is required.**

https://wiki.python.org/moin/WindowsCompilers

> Even though Python is an interpreted language, you may need to install Windows C++ compilers in some cases. Unlike Linux, compilers for Windows are not included by default in the OS.

**Comment by xiezhoubin** [comment]
> @xiezhoubin You can see a package files of zipfile-deflate64 at https://pypi.org/project/zipfile-deflate64/#files
> 
> Because there are no 32bit binaries, you tried to install it from source. It is what your log message said.
> 
> ```
> building 'zipfile_deflate64.deflate64' extension
> error: Microsoft Visual C++ 14.0 or greater is required.
> ```
> 
> > **Microsoft Visual C++ 14.0 or greater is required.**
> 
> https://wiki.python.org/moin/WindowsCompilers
> 
> > Even though Python is an interpreted language, you may need to install Windows C++ compilers in some cases. Unlike Linux, compilers for Windows are not included by default in the OS.

Yes, you can install "py7zr" by installing "Microsoft Visual c++ 14.0".

**Comment by cielavenir** [comment]
oh... sorry...

at https://github.com/cielavenir/zipfile39/actions/runs/2016136704 "windows_wheel" you can find zipfile_deflate64-0.2.0.5.dev7+gd851218-cp37-cp37m-win32.whl and you can install it...

@brianhelba meanwhile could you consider adding win32 wheel to pypi?

**Comment by miurahr** [comment]
I've raised  an issue ticket on zipfile-deflate64 project.

**Comment by miurahr** [comment]
Same issue can be happened for aarch64 (M1/M2 mac) and musllinux (popular linux distro in docker container).

**Comment by cielavenir** [comment]
for macosx aarch64, seems github-action will be resolved soon

**Comment by miurahr** [comment]
resolved in new releases.
