### ISSUE TITLE
Does it support decompression progress display?

### ISSUE THREAD

**Issue by boynton89** [miurahr/py7zr#460]
Does it support decompression progress display?

**Comment by miurahr** [comment]
@boynton89 you can see callback API that give you a way to get a progress.

https://github.com/miurahr/py7zr/blob/96c2745de6f73d65aff7f652f414681c29e9b571/tests/test_misc.py#L129-L152

This test case define a class ``ECB`` that print callback message to ``stdout``, inherited from ``ExtractCallBack``, and pass its instance to ``extractall`` method.

**Comment by miurahr** [comment]
A CLI does not implement it yet.
