### ISSUE TITLE
Information about license needs to be updated

### ISSUE THREAD

**Issue by kachura1986** [miurahr/py7zr#469]
Hello!
I think, information about license needs to be updated:
7-Zip Copyright (C) 1999-2010 Igor Pavlov ->  7-Zip Copyright (C) 1999-2022 Igor Pavlov
LZMA SDK Copyright (C) 1999-2010 Igor Pavlov -> LZMA SDK Copyright (C) 1999-2022 Igor Pavlov

**Comment by miurahr** [comment]
py7zr refer the code in pylzma. There is no problem.
