### ISSUE TITLE
py7zr allows creating 7z archives with stored absolute paths, then always produces an error for extracting (reading) them

### ISSUE THREAD

**Issue by NixSar** [miurahr/py7zr#525]
**Describe the bug**

Extracting 7z archive with stored absolute paths to another absolute path always produces an error

**Related issue**

**To Reproduce**

1. Create archive test.7z with the code attached below
2. Try to restore archive test.7z to a new path using the code attached below
3.  Produces error:
```
Traceback (most recent call last):
  File "test_archives.py", line 31, in <module>
    archive.extractall(destination_path)
  File "...\Lib\site-packages\py7zr\py7zr.py", line 963, in extractall
    self._extract(path=path, return_dict=False, callback=callback)
  File "...\Lib\site-packages\py7zr\py7zr.py", line 577, in _extract
    outfilename = get_sanitized_output_path(outname, path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Lib\site-packages\py7zr\helpers.py", line 481, in get_sanitized_output_path
    raise Bad7zFile(f"Specified path is bad: {fname}")
py7zr.exceptions.Bad7zFile: Specified path is bad: C:/test/PineTools.com_files
```

**Expected behavior**
Files stored in test.7z are restored to the path 'C:\\test-new\\'

**Environment (please complete the following information):**
 - OS: Windows 11
 - Python 3.11.0
 - py7zr version: 0.20.5

**Test data(please attach in the report):**
1. [source.zip](https://github.com/miurahr/py7zr/files/11951821/source.zip)
2. [test.zip](https://github.com/miurahr/py7zr/files/11951830/test.zip)

**Additional context**

**Comment by NixSar** [comment]
Actually, on further testing, any kind of read operations produce the same error. The archive works perfectly fine outside of py7zr.

**Comment by ddalcino** [comment]
The `get_sanitized_output_path` call exists to protect your system from malicious `.7z` files that are designed to overwrite sensitive files on your system. You would not be pleased if you unzipped an archive and it started overwriting files in `c:\windows\system32`, would you? The most effective way to prevent this kind of attack is not to allow absolute paths.

If you want to extract files to the `C:\test-new\` directory, I suggest compressing files using relative paths, and setting the output directory as a command line argument:

```cmd
C:\> py7zr x test.zip C:\test-new
```

**Comment by NixSar** [comment]
> The `get_sanitized_output_path` call exists to protect your system from malicious `.7z` files that are designed to overwrite sensitive files on your system. You would not be pleased if you unzipped an archive and it started overwriting files in `c:\windows\system32`, would you? The most effective way to prevent this kind of attack is not to allow absolute paths.
> 
> If you want to extract files to the `C:\test-new\` directory, I suggest compressing files using relative paths, and setting the output directory as a command line argument:
> 
> ```batchfile
> C:\> py7zr x test.zip C:\test-new
> ```

If this is a feature and not a bug, it must be better documented and the error messages made much clearer. Also, pretty much every library that works with compressed archives in Python allows this, from zipfile to tarfile. It should at least be optional, since I use it on my own computer, for my own scripts to do my own backup and the security risks are minimal.

**Comment by miurahr** [comment]
The change was introduced when a security advisory issued;  
[py7zr directory traversal vulnerability](https://github.com/advisories/GHSA-m8xw-9x5x-6vh3)

I've checked archive paths. I've taken strict policy  to check that extraction should be in specified target folder.
All others should become error.

**Comment by ddalcino** [comment]
> If this is a feature and not a bug, it must be better documented and the error messages made much clearer.

I agree that the error message could be improved.

I am not so sure that this needs to go in the documentation. In 2023, it should be expected that any default configuration will protect you from malicious archives.

If you want this behavior to be better documented, what would you want it to say, and where would you put it?

> Also, pretty much every library that works with compressed archives in Python allows this, from zipfile to tarfile.

What libraries/versions are these? This is a serious security issue, and worth patching.

> It should at least be optional, since I use it on my own computer, for my own scripts to do my own backup and the security risks are minimal.

So you're asking for a new CLI flag that lets you turn off the security feature? What useful benefit would this have that can't be done with relative paths?

**Comment by NixSar** [comment]
> > If this is a feature and not a bug, it must be better documented and the error messages made much clearer.
> 
> I agree that the error message could be improved.
> 
> I am not so sure that this needs to go in the documentation. In 2023, it should be expected that any default configuration will protect you from malicious archives.
> 
> If you want this behavior to be better documented, what would you want it to say, and where would you put it?
> 
> > Also, pretty much every library that works with compressed archives in Python allows this, from zipfile to tarfile.
> 
> What libraries/versions are these? This is a serious security issue, and worth patching.
> 
> > It should at least be optional, since I use it on my own computer, for my own scripts to do my own backup and the security risks are minimal.
> 
> So you're asking for a new CLI flag that lets you turn off the security feature? What useful benefit would this have that can't be done with relative paths?

I guess I am either very ignorant, I am not being ironic, or we are misunderstanding each other, but every library I've ever used including [zipfile](https://docs.python.org/3/library/zipfile.html), standard Python library for operating with zip archives, allows the behavior I am describing with compressed archives. Also, the archives made in this way can be opened and extracted with any program supporting 7z archives except in py7zr. I am probably missing something crucial here. Did you look at my attached code and archive? This same code works anywhere else, and also produces archives openable and extractable with any type of path anywhere else except by py7zr.

As to the benefit, I was trying to use py7zr in my backup script, but I have now switched to zipfile and tarfile that work perfectly. If I store absolute paths in my archives, I don't need to either store them somewhere else, like in a separate JSON or XML or database, nor add complexity to my code to translate base paths (how I identify backups) into relative paths, and since I am backing up programs with very strict structures, this is important. Also, when I am doing restore, sometimes I want to restore them to another absolute path completely different to the one stored in the archive.

**Comment by miurahr** [comment]
I think python designs zipfile/tarfile not to allow malicious archive to be extracted.
Here is a Python zipfile  and tarfile manual descriptions.

https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.extract

>> Note If a member filename is an absolute path, a drive/UNC sharepoint and leading (back)slashes will be stripped, e.g.: ///foo/bar becomes foo/bar on Unix, and C:\foo\bar becomes foo\bar on Windows. And all ".." components in a member filename will be removed, e.g.: ../../foo../../ba..r becomes foo../ba..r. On Windows illegal characters (:, <, >, |, ", ?, and *) replaced by underscore (_).

https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter

> The tar format is designed to capture all details of a UNIX-like filesystem, which makes it very powerful. Unfortunately, the features make it easy to create tar files that have unintended – and possibly malicious – effects when extracted. For example, extracting a tar file can overwrite arbitrary files in various ways (e.g. by using absolute paths, .. path components, or symlinks that affect later members).
>
> In most cases, the full functionality is not needed. Therefore, tarfile supports extraction filters: a mechanism to limit functionality, and thus mitigate some of the security issues.
>
> See also
> [PEP 706](https://peps.python.org/pep-0706/) Contains further motivation and rationale behind the design.
>
> The filter argument to [TarFile.extract()](https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.extract) or  [extractall()](https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.extractall) can be:
>
> the string 'fully_trusted': Honor all metadata as specified in the archive. Should be used if the user trusts the archive completely, or implements their own complex verification.
>
> the string 'tar': Honor most tar-specific features (i.e. features of UNIX-like filesystems), but block features that are very likely to be surprising or malicious. See [tar_filter()](https://docs.python.org/3/library/tarfile.html#tarfile.tar_filter) for details.
>
> the string 'data': Ignore or block most features specific to UNIX-like filesystems. Intended for extracting cross-platform data archives. See [data_filter()](https://docs.python.org/3/library/tarfile.html#tarfile.data_filter) for details.

https://docs.python.org/3/library/tarfile.html#tarfile.tar_filter

> Strip leading slashes (/ and [os.sep](https://docs.python.org/3/library/os.html#os.sep)) from filenames.
> [Refuse](https://docs.python.org/3/library/tarfile.html#tarfile-extraction-refuse) to extract files with absolute paths (in case the name is absolute even after stripping slashes, e.g. C:/foo on Windows). This raises [AbsolutePathError](https://docs.python.org/3/library/tarfile.html#tarfile.AbsolutePathError).
>  **[Refuse](https://docs.python.org/3/library/tarfile.html#tarfile-extraction-refuse) to extract files whose absolute path (after following symlinks) would end up outside the destination.** This raises [OutsideDestinationError](https://docs.python.org/3/library/tarfile.html#tarfile.OutsideDestinationError).
> Clear high mode bits (setuid, setgid, sticky) and group/other write bits (S_IWOTH).

**Comment by NixSar** [comment]
You are, of course, right. That is why I am saying, I might be missing something very obvious, but the code I provided works just fine with zipfile and tarfile, but fails with py7zr.

**Comment by ddalcino** [comment]
> You are, of course, right. That is why I am saying, I might be missing something very obvious, but the code I provided works just fine with zipfile and tarfile, but fails with py7zr.

You are correct in that `zipfile` and `tarfile` handle absolute paths differently than `py7zr` does. By default, both `zipfile` and `tarfile` will transform absolute paths into relative paths. In contrast, `py7zr` will outright reject absolute paths and raise `Bad7zFile`.

IMHO `py7zr`'s behavior is not wrong. I prefer having interfaces that tell you that something went wrong and what it was, as opposed to something like `zipfile` that silently "fixes it for you" in a way that you may or may not expect or want. However, there's also a lot of value in keeping `py7zr`'s external interface as similar as possible to interfaces that already exist in the standard library, and that's probably more important than my personal opinions.

I think it would be easy enough to use something like the existing `zipfile` sanitizer methods, `_sanitize_filename` and `_sanitize_windows_name`, and use those paths instead of raising `Bad7zFile`. Reference below.

https://github.com/python/cpython/blob/b9c9a36c2f2edc11b9c27eb7c5810919d9da9767/Lib/zipfile/__init__.py#L341C1-L358C1
```python
def _sanitize_filename(filename):
    """Terminate the file name at the first null byte and
    ensure paths always use forward slashes as the directory separator."""

    # Terminate the file name at the first null byte.  Null bytes in file
    # names are used as tricks by viruses in archives.
    null_byte = filename.find(chr(0))
    if null_byte >= 0:
        filename = filename[0:null_byte]
    # This is used to ensure paths in generated ZIP files always use
    # forward slashes as the directory separator, as required by the
    # ZIP format specification.
    if os.sep != "/" and os.sep in filename:
        filename = filename.replace(os.sep, "/")
    if os.altsep and os.altsep != "/" and os.altsep in filename:
        filename = filename.replace(os.altsep, "/")
    return filename
```

https://github.com/python/cpython/blob/b9c9a36c2f2edc11b9c27eb7c5810919d9da9767/Lib/zipfile/__init__.py#L1722C1-L1736C1
```python
   @classmethod
    def _sanitize_windows_name(cls, arcname, pathsep):
        """Replace bad characters and remove trailing dots from parts."""
        table = cls._windows_illegal_name_trans_table
        if not table:
            illegal = ':<>|"?*'
            table = str.maketrans(illegal, '_' * len(illegal))
            cls._windows_illegal_name_trans_table = table
        arcname = arcname.translate(table)
        # remove trailing dots and spaces
        arcname = (x.rstrip(' .') for x in arcname.split(pathsep))
        # rejoin, removing empty parts.
        arcname = pathsep.join(x for x in arcname if x)
        return arcname
```

**Comment by NixSar** [comment]
I still think I wasn't clear enough and why I think this is a bug, or poorly documented or handled (pick whichever one). This "malicious" archive with absolute paths is happily created by py7zr by my script. Why does py7zr allow making of archives with absolute paths without a single warning that it later refuses to open or extract in any way? This doesn't sound like a properly handled situation to me. Either reject it outright, warn the user, or handle it silently and convert to relative paths like zipfile or tarfile.

**Comment by miurahr** [comment]
> This "malicious" archive with absolute paths is happily created by py7zr by my script. 

If so it is bug. Could you provide a reproducible script?

**Comment by NixSar** [comment]
> > This "malicious" archive with absolute paths is happily created by py7zr by my script.
> 
> If so it can be a bug. Could you provide a reproducible script?

I have already in my original post. test_archives.py produces and archive that cannot be extracted later.

**Comment by miurahr** [comment]
```
import py7zr
import os
import traceback

# Hardcoded directory to archive
source_dir = os.path.normpath("C:\\test\\PineTools.com_files")

# Hardcoded 7z archive file name
archive_file = os.path.normpath("D:\\test\\Backups\\PineTools.com\\test.7z")

# New destination path for extracted files
destination_path = os.path.normpath("C:\\test-new\\")

# Create the destination directory if it doesn't exist
if not os.path.exists(destination_path):
    os.makedirs(destination_path)

# Create the 7z archive file
with py7zr.SevenZipFile(archive_file, mode='w') as archive:
    try:
        # Add all files in the source directory to the archive
        archive.writeall(source_dir)
    except py7zr.exceptions.Bad7zFile as e:
        # Handle the Bad7zFile exception
        print(f"Error creating 7z archive: {e}")

# Open the 7z archive file
with py7zr.SevenZipFile(archive_file, mode='r') as archive:
    try:
        # Extract all files to the new destination path
        archive.extractall(destination_path)
    except py7zr.exceptions.Bad7zFile as e:
        # Print the traceback for the Bad7zFile exception
        traceback.print_exc()
```

**Comment by miurahr** [comment]
From document,
https://py7zr.readthedocs.io/en/latest/api.html#py7zr.SevenZipFile.writeall

> Write the directory and its sub items recursively into the archive, giving the archive name arcname (by default, this will be the same as filename, but without a drive letter and with leading path seaprator removed).
>
> If you want to store directories and files, putting arcname is good idea. When filename is ‘C:/a/b/c’ and arcname is ‘c’, with a file exist as ‘C:/a/b/c/d.txt’, then archive listed as [‘c’, ‘c/d.txt’], the former as directory.

When the description is correct, py7zr should not generate an archive with full path.

**Comment by miurahr** [comment]
I've pushed PR that try  sanitizing an archive name.

**Comment by NixSar** [comment]
**Update**: the new version sanitizes paths prior to write and produces readable archives, but py7zr behavior is still different to zipfile and tarfile, which is probably fine, but I just wanted to document it here. zipfile and tarfile sanitized absolute paths produce correct original absolute paths when extracted, while py7zr always extracts only to current directory, meaning it "forgets" the original absolute path.
