### ISSUE TITLE
extractall callback more frequent progress reports for large files

### ISSUE THREAD

**Issue by MBradbury** [miurahr/py7zr#526]
The ExtractCallback supports events at both the start and end of decompressing a file in an archive. When an archive contains very large files events are not sent to the callback frequently enough to be able to display suitable progress updates. For example in my use-case an archive contains a small (3 KB) file and a large (~14 GB) file, two `report_end` events will occur for each file.

It would be useful for ExtractCallback to support a `report_intermediate` or similar that will report written bytes. This could be periodically based on time or bytes written to disk.

Using tqdm to render a progress bar, I get output three times such as the following, which is not frequent enough to indicate to users that progress is occurring.

Extracting:   0%|                                         | 0.00/13.8G [00:00<?, ?B/s]
Extracting:   0%|                            | 3.02k/13.8G [00:00<390:27:28, 9.84kB/s]
Extracting: 100%|████████████████████████████████| 13.8G/13.8G [11:53<00:00, 19.4MB/s]

```python
import py7zr
from tqdm import tqdm

class ExtractProgressBar(py7zr.callbacks.ExtractCallback, tqdm):
    def __init__(self, *args, total_bytes, **kwargs):
        super().__init__(self, *args, total=total_bytes, **kwargs)

    def report_start_preparation(self):
        pass

    def report_start(self, processing_file_path, processing_bytes):
        pass

    def report_end(self, processing_file_path, wrote_bytes):
        print()
        self.update(int(wrote_bytes))

    def report_postprocess(self):
        pass

    def report_warning(self, message):
        pass

with py7zr.SevenZipFile("archive.7z", 'r') as archive:
    archive_info = archive.archiveinfo()
    with ExtractProgressBar(
             unit='B',
             unit_scale=True,
             miniters=1,
             total_bytes=archive_info.uncompressed,
             desc=f"Extracting") as progress:
        archive.extractall(path=destination, callback=progress)
```

**Comment by WeiqiangChen** [comment]
Hi, Is it possible to add a progress bar for compressing zip files.
I have the following code to compress all files in a folder except some folders and some files. Have googled but could not find a solution to add a progress bar when there are >100MB files to compress. 

```
import py7zr
import os

target_dir = "C:/test/WeiQiang_Python"
zipfilename = f"{target_dir}/{os.path.basename(target_dir)}.7z"

with py7zr.SevenZipFile(zipfilename, "w") as zipfile:
    for dirpath, _, filenames in os.walk(target_dir):
        for filename in filenames:
            filepath = os.path.join(dirpath, filename)
            if (
                ".7z" not in filepath
                and "\\data\\raw\\" not in filepath
                and "-decoys-combined" not in filepath
            ):
                inzippath = filepath.replace(target_dir, "")
                zipfile.write(filepath, inzippath)
```

**Comment by YeeaaahMan** [comment]
I have the same issue: 4.5GB 7z-archive wich contains 4 GB app-file. 
We use different impementation of progress bar. But numbers still look weird.
```
Extract SevenZipFile /Users/s_litvinchuk/Downloads/_build_Mac-4626.7z to folder temp
0.0 %
10.0 %
100.0 %
```
I will try to support this case in pr #558 =)

**Comment by YeeaaahMan** [comment]
PR was merged. Issue could be closed.
