### ISSUE TITLE
py7zr fail to load on azure vm, because dependency brotli failed to load brotli DLL

### ISSUE THREAD

**Issue by yannou38** [miurahr/py7zr#527]
**Describe the bug**

On an Azure VM, py7zr couldn't load due to the brotlicffi module missing

**Related issue**
Found while looking at [this issue](https://github.com/miurahr/aqtinstall/issues/696).

**To Reproduce**
Unsure. Try to install py7zr on a newly created azure VM and call "python -m py7zr i" could trigger the error ?

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Azure VM Windows
 - Python 3.11.1
 - py7zr version: 0.20.5

**Additional context**
Additional context can be found in linked issue

**Comment by miurahr** [comment]
brotlicffi is dependency for pypy, but you use CPython and log show a successful install of Brotli library.
It seems a problem where importing brotli library.

**Comment by miurahr** [comment]
Latest CI test is passed with brotli 1.0.9 on Python 3.11.4 on Windows in 3 weeks ago.
brotli 1.0.9 is latest version.

**Comment by miurahr** [comment]
There is a similar bug issue in brotli project.
https://github.com/google/brotli/issues/782#issuecomment-559516099

said


> Maybe you're system is missing the visual c++ redistributable DLLs (though I think python itself should come with one).
> You said 64-bit, try to install the current "vc_redist.x64.exe" from this link
> https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads
>

**Comment by miurahr** [comment]
@yannou38 does #543 solve your issue?
