### ISSUE TITLE
Please consider removing 0.9.5 -> 0.11.2 packages from pypi.org (malware test cases)

### ISSUE THREAD

**Issue by scovetta** [miurahr/py7zr#532]
**Describe the bug**

Due to [#285](https://github.com/miurahr/py7zr/issues/285) and the information in the README, I'd like to ask you to consider removing/disabling the affected versions of py7zr from the public pypi.org registry.

As far I can tell from the [README](https://github.com/miurahr/py7zr/blob/4bba07d64d84698c4bef44622885a387b8602d03/README.rst#warning), affected packages include the .tar.gz distributions for these versions:

- 0.9.5
- 0.9.6
- 0.9.7
- 0.9.8
- 0.9.9
- 0.10.0
- 0.10.0a1
- 0.10.0a2
- 0.10.0a3
- 0.10.0a4
- 0.10.0a5
- 0.10.0a6
- 0.10.0b1
- 0.10.0b3
- 0.10.1
- 0.11.0
- 0.11.0a1
- 0.11.0b1
- 0.11.0b2
- 0.11.0b3
- 0.11.1
- 0.11.2

**Related issue**
- [#285](https://github.com/miurahr/py7zr/issues/285)

**To Reproduce**
1. Open the PyPI registry for this package.
2. Navigate to version 0.11.0.
3. Download the source distribution.
4. See your anti-virus software complain.

**Expected behavior**
The affected packages should not be available for installation on pypi.org.

**Environment (please complete the following information):**
N/A

**Test data(please attach in the report):**
N/A

**Additional context**
Showing downloading the affected file and watching Clamscan complain

```
# This is the URL found here: https://pypi.org/project/py7zr/0.11.0/#files
root@1e76bdff2f38:/usr/src/app# wget 'https://files.pythonhosted.org/packages/bc/dd/296e18866a1953ff5fa58be625ada4f6d501c65927085578899ec07b9650/py7zr-0.11.0.tar.gz'
--2023-08-21 21:03:04--  https://files.pythonhosted.org/packages/bc/dd/296e18866a1953ff5fa58be625ada4f6d501c65927085578899ec07b9650/py7zr-0.11.0.tar.gz
Resolving files.pythonhosted.org (files.pythonhosted.org)... 146.75.33.55, 2a04:4e42:78::311
Connecting to files.pythonhosted.org (files.pythonhosted.org)|146.75.33.55|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2775707 (2.6M) [application/x-tar]
Saving to: 'py7zr-0.11.0.tar.gz'

py7zr-0.11.0.tar.gz           100%[=================================================>]   2.65M  --.-KB/s    in 0.1s

2023-08-21 21:03:04 (19.1 MB/s) - 'py7zr-0.11.0.tar.gz' saved [2775707/2775707]

root@1e76bdff2f38:/usr/src/app# clamscan py7zr-0.11.0.tar.gz
LibClamAV Warning: **************************************************
LibClamAV Warning: ***  The virus database is older than 7 days!  ***
LibClamAV Warning: ***   Please update it as soon as possible.    ***
LibClamAV Warning: **************************************************
/usr/src/app/py7zr-0.11.0.tar.gz: Win.Dropper.Tiggre-9845940-0 FOUND

----------- SCAN SUMMARY -----------
Known viruses: 8667807
Engine version: 0.103.8
Scanned directories: 0
Scanned files: 1
Infected files: 1
Data scanned: 3.63 MB
Data read: 2.64 MB (ratio 1.37:1)
Time: 9.756 sec (0 m 9 s)
Start Date: 2023:08:21 21:03:13
End Date:   2023:08:21 21:03:23
```

**Comment by miurahr** [comment]
Yank all the affected versions. Done...

**Comment by miurahr** [comment]
Thanks!

**Comment by scovetta** [comment]
Thank you very much!
