### ISSUE TITLE
Bug in _filelist_retrieve and extractall

### ISSUE THREAD

**Issue by eugenkleinschmidt** [miurahr/py7zr#54]
**Describe the bug**
This bug is present when main_streams is None. Check against None is needed.
![image](https://user-images.githubusercontent.com/10838796/72989268-3a6db300-3dee-11ea-96fe-f0370a012588.png)

and in extractall
![image](https://user-images.githubusercontent.com/10838796/72988913-85d39180-3ded-11ea-8c93-ecc978481550.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python 3.8
 - py7zr version: v0.5b5

**Test data(please attach in the report):**
[test_data.zip](https://github.com/miurahr/py7zr/files/4103305/test_data.zip)

**Comment by miurahr** [comment]
Thank you for detailed report! Confirmed.
It is happened when there are files and directories with ZERO size, then archive does not have a actual data, which main_streams holds.
