### ISSUE TITLE
Python "zipfile" compatibility

### ISSUE THREAD

**Issue by upadsamay387** [miurahr/py7zr#553]
Hi, I'm writing a script that handles multiple archive file types, and while zipfile and rarfile have the same methods and seemingly similar implementations, py7zr does not. This makes it a little annoying to make helper methods as I always have to handle incompatibilities between py7zr and other libraries.

For example:

>def _copy_helper(archive, dst, member_prefix):
>>for file in archive.namelist():
>>>...

Works fine for zipfile and rarfile, but not in py7zr since namelist() isn't implemented.

**Comment by miurahr** [comment]
Thank you for suggestion. As always, your contribution and Pull-Request are welcome!
py7zr has already implement a feature which list a files in CLI, it will be very easy to implement the feature.

**Comment by Ravencentric** [comment]
`SevenZipFile.getnames()` is the equivalent of `ZipFile.namelist()`. I had the same issue and ended up writing a wrapper for common archive formats [here](https://github.com/Ravencentric/archivefile).

**Comment by miurahr** [comment]
A feature is implemented and released v1.0.0-rc1
