### ISSUE TITLE
Python 3.7 is not supported in version 0.21.0

### ISSUE THREAD

**Issue by noneghost** [miurahr/py7zr#594]
**Describe the bug**
Since the version of the dependent pyppdm is limited to >1.1.0, 0.21.0 will not support Python 3.7

**Related issue**

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**
 - OS: 
 - Python python3.7.9 
 - py7zr version: 

**Test data(please attach in the report):**

**Additional context**

**Comment by miurahr** [comment]
Python 3.7 is ended in 27 Jun 2023

**Comment by miurahr** [comment]
v0.22.0 explicitly drop a support for python3.7.
