### ISSUE TITLE
ArchiveInfo.solid - Wrong result

### ISSUE THREAD

**Issue by ganego** [miurahr/py7zr#72]
**Describe the bug**
`ArchiveInfo.solid` gives wrong result.

**To Reproduce**
I created an archive of 12 jpeg files, for a total of 32 MB with 7z 19.00, compression level: Fastest, Solid Block Size: 8 MB.  
I verified in 7z that the archive is indeed solid (Info button -> solid had a `+`).

```
import py7zr
sz = py7zr.SevenZipFile(path)
print(sz.archiveinfo().solid)
```

Returns False for those archives, despite them being solid.

**Environment (please complete the following information):**
 - OS: [W7x64]
 - Python [Python 3.8.1 x64]
 - py7zr version: [py7zr-0.5-py3-none-any from pip]

**Comment by ganego** [comment]
This is the code from \CPP\7zip\Archive\7z\7zIn.h in case it helps.

```
  bool IsSolid() const
  {
    for (CNum i = 0; i < NumFolders; i++)
      if (NumUnpackStreamsVector[i] > 1)
        return true;
    return false;
  }
```

**Comment by miurahr** [comment]
@ganego  could you check PR #97 ?

**Comment by ganego** [comment]
@miurahr I tested with a couple of different 7z archives and it seems to work.  
Thank you for investing your time and creating this library :)
