### ISSUE TITLE
Extract single file from archive

### ISSUE THREAD

**Issue by svidoso** [miurahr/py7zr#76]
**Is your feature request related to a problem? Please describe.**
Sometimes just one file from a large archive must be extracted.

**Describe the solution you'd like**
Add extract_single method to SevenZipFile class.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by miurahr** [comment]
You can extract single file from archive.
```
archive = SevenZipFile('archive.7z', 'r')
    allfiles = archive.getnames()
    filter_pattern = re.compile(r'<your/target/file_and_directories/regex/expression>*')
    targets = []
    for f in allfiles:
        if filter_pattern.match(f):
            targets.append(f)
    archive.extract(path=tmp_path, targets=targets)
    archive.close()
```

**Comment by svidoso** [comment]
Thanks, that works!
